root 2023-12-25 12:29:44,706 INFO siteInsertOrders(). Podkluchenie k base site i otptavka zaprosa.
paramiko.transport 2023-12-25 12:29:44,739 INFO Connected (version 2.0, client OpenSSH_7.4)
paramiko.transport 2023-12-25 12:29:45,096 INFO Authentication (password) successful!
root 2023-12-25 12:29:49,096 INFO siteInsertOrders(). Uspeshnoe poluchenie dannih.
root 2023-12-25 12:29:49,099 INFO site.dataSiteToBd(). Zapis dataframe v tablitsu site_insert_order_new.
root 2023-12-25 12:29:49,198 ERROR site.dataSiteToBd(). Oshibka zapisi dannih v tab site_insert_order_new - (psycopg2.errors.StringDataRightTruncation) value too long for type character(1)

[SQL: INSERT INTO public.site_insert_order_new (order_id, user_id, status_id, account_number, additional_info, affiliate_id, allow_delivery, bx_user_id, canceled, comments, company_id, created_by, currency, date_allow_delivery, date_bill, date_canceled, da ... 81659 characters truncated ... (updated_1c__48)s, %(user_description__48)s, %(version__48)s, %(version_1c__48)s, %(promocode__48)s)]
[parameters: {'price_delivery__0': Decimal('0.0000'), 'pay_voucher_date__0': None, 'recurring_id__0': None, 'date_deducted__0': None, 'is_recurring__0': 'N', 'delivery_doc_num__0': None, 'status_id__0': 'OR', 'allow_delivery__0': 'N', 'reason_undo_deducted__0': None, 'comments__0': '¹# new_IM-123', 'reserved__0': 'N', 'payed__0': 'N', 'user_description__0': None, 'is_sync_b24__0': 'N', 'ps_status_code__0': None, 'delivery_doc_date__0': None, 'promocode__0': None, 'ps_status_description__0': None, 'tracking_number__0': None, 'delivery_id__0': '24', 'sum_paid__0': Decimal('0.00'), 'date_bill__0': None, 'price__0': Decimal('4380.0000'), 'updated_1c__0': 'Y', 'date_insert__0': datetime.datetime(2023, 12, 24, 1, 9, 25), 'recount_flag__0': 'Y', 'ps_status__0': None, 'discount_value__0': Decimal('0.0000'), 'ps_sum__0': None, 'account_number__0': 'IM-12322243', 'responsible_id__0': None, 'date_payed__0': None, 'pay_system_id__0': 1, 'date_marked__0': None, 'date_status__0': datetime.datetime(2023, 12, 24, 1, 9, 37), 'person_type_id__0': 1, 'additional_info__0': None, 'stat_gid__0': 'BITRIX_SM.NTU0ODk0Ni42NjA2NDIuS1ouLi5zMQ==', 'tax_value__0': Decimal('0.00'), 'date_lock__0': None, 'emp_deducted_id__0': None, 'company_id__0': 0, 'affiliate_id__0': None, 'ps_status_message__0': None, 'price_payment__0': Decimal('0.0000'), 'created_by__0': 106824, 'reason_canceled__0': '¹# new_IM-123', 'version_1c__0': None, 'ps_currency__0': None, 'date_update__0': datetime.datetime(2023, 12, 24, 1, 9, 40) ... 3673 parameters truncated ... 'discount_value__48': Decimal('0.0000'), 'ps_sum__48': None, 'account_number__48': 'IM-12322291', 'responsible_id__48': None, 'date_payed__48': None, 'pay_system_id__48': 1, 'date_marked__48': None, 'date_status__48': datetime.datetime(2023, 12, 25, 11, 18, 25), 'person_type_id__48': 1, 'additional_info__48': None, 'stat_gid__48': 'BITRIX_SM.NTU1NTc0OC4xNzMwNjcxLlJVLi4uczE=', 'tax_value__48': Decimal('0.00'), 'date_lock__48': None, 'emp_deducted_id__48': None, 'company_id__48': 0, 'affiliate_id__48': None, 'ps_status_message__48': None, 'price_payment__48': Decimal('0.0000'), 'created_by__48': 139357, 'reason_canceled__48': None, 'version_1c__48': None, 'ps_currency__48': None, 'date_update__48': datetime.datetime(2023, 12, 25, 11, 18, 27), 'emp_status_id__48': 4, 'date_pay_before__48': None, 'version__48': 105, 'emp_canceled_id__48': None, 'emp_allow_delivery_id__48': None, 'pay_voucher_num__48': None, 'currency__48': 'RUB', 'lid__48': 's1', 'id_1c__48': '118582', 'deducted__48': 'N', 'emp_payed_id__48': None, 'search_content__48': None, 'order_id__48': 322291, 'ps_response_date__48': None, 'reason_marked__48': None, 'external_order__48': 'N', 'store_id__48': None, 'date_allow_delivery__48': None, 'marked__48': 'N', 'bx_user_id__48': 'c25d82068abec5df82bfb723bc95edae', 'running__48': 'N', 'user_id__48': 139357, 'order_topic__48': None, 'date_canceled__48': None, 'locked_by__48': None, 'canceled__48': 'N', 'emp_marked_id__48': None}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
Traceback (most recent call last):
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 2112, in _exec_insertmany_context
    dialect.do_execute(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.StringDataRightTruncation: value too long for type character(1)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "g:\py.projects\tb\data_collection\site_dat\load_data_site.py", line 95, in dataSiteToBd
    df.to_sql(tableName, engine_pg, schema='public', if_exists='append', index=False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\core\generic.py", line 3008, in to_sql
    return sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1958, in to_sql
    total_inserted = sql_engine.insert_records(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1507, in insert_records
    raise err
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1498, in insert_records
    return table.insert(chunksize=chunksize, method=method)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1059, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 951, in _execute_insert
    result = conn.execute(self.table.insert(), data)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\sql\elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1639, in _execute_clauseelement
    ret = self._execute_context(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1843, in _execute_context
    return self._exec_insertmany_context(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 2120, in _exec_insertmany_context
    self._handle_dbapi_exception(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 2343, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 2112, in _exec_insertmany_context
    dialect.do_execute(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError: (psycopg2.errors.StringDataRightTruncation) value too long for type character(1)

[SQL: INSERT INTO public.site_insert_order_new (order_id, user_id, status_id, account_number, additional_info, affiliate_id, allow_delivery, bx_user_id, canceled, comments, company_id, created_by, currency, date_allow_delivery, date_bill, date_canceled, da ... 81659 characters truncated ... (updated_1c__48)s, %(user_description__48)s, %(version__48)s, %(version_1c__48)s, %(promocode__48)s)]
[parameters: {'price_delivery__0': Decimal('0.0000'), 'pay_voucher_date__0': None, 'recurring_id__0': None, 'date_deducted__0': None, 'is_recurring__0': 'N', 'delivery_doc_num__0': None, 'status_id__0': 'OR', 'allow_delivery__0': 'N', 'reason_undo_deducted__0': None, 'comments__0': '¹# new_IM-123', 'reserved__0': 'N', 'payed__0': 'N', 'user_description__0': None, 'is_sync_b24__0': 'N', 'ps_status_code__0': None, 'delivery_doc_date__0': None, 'promocode__0': None, 'ps_status_description__0': None, 'tracking_number__0': None, 'delivery_id__0': '24', 'sum_paid__0': Decimal('0.00'), 'date_bill__0': None, 'price__0': Decimal('4380.0000'), 'updated_1c__0': 'Y', 'date_insert__0': datetime.datetime(2023, 12, 24, 1, 9, 25), 'recount_flag__0': 'Y', 'ps_status__0': None, 'discount_value__0': Decimal('0.0000'), 'ps_sum__0': None, 'account_number__0': 'IM-12322243', 'responsible_id__0': None, 'date_payed__0': None, 'pay_system_id__0': 1, 'date_marked__0': None, 'date_status__0': datetime.datetime(2023, 12, 24, 1, 9, 37), 'person_type_id__0': 1, 'additional_info__0': None, 'stat_gid__0': 'BITRIX_SM.NTU0ODk0Ni42NjA2NDIuS1ouLi5zMQ==', 'tax_value__0': Decimal('0.00'), 'date_lock__0': None, 'emp_deducted_id__0': None, 'company_id__0': 0, 'affiliate_id__0': None, 'ps_status_message__0': None, 'price_payment__0': Decimal('0.0000'), 'created_by__0': 106824, 'reason_canceled__0': '¹# new_IM-123', 'version_1c__0': None, 'ps_currency__0': None, 'date_update__0': datetime.datetime(2023, 12, 24, 1, 9, 40) ... 3673 parameters truncated ... 'discount_value__48': Decimal('0.0000'), 'ps_sum__48': None, 'account_number__48': 'IM-12322291', 'responsible_id__48': None, 'date_payed__48': None, 'pay_system_id__48': 1, 'date_marked__48': None, 'date_status__48': datetime.datetime(2023, 12, 25, 11, 18, 25), 'person_type_id__48': 1, 'additional_info__48': None, 'stat_gid__48': 'BITRIX_SM.NTU1NTc0OC4xNzMwNjcxLlJVLi4uczE=', 'tax_value__48': Decimal('0.00'), 'date_lock__48': None, 'emp_deducted_id__48': None, 'company_id__48': 0, 'affiliate_id__48': None, 'ps_status_message__48': None, 'price_payment__48': Decimal('0.0000'), 'created_by__48': 139357, 'reason_canceled__48': None, 'version_1c__48': None, 'ps_currency__48': None, 'date_update__48': datetime.datetime(2023, 12, 25, 11, 18, 27), 'emp_status_id__48': 4, 'date_pay_before__48': None, 'version__48': 105, 'emp_canceled_id__48': None, 'emp_allow_delivery_id__48': None, 'pay_voucher_num__48': None, 'currency__48': 'RUB', 'lid__48': 's1', 'id_1c__48': '118582', 'deducted__48': 'N', 'emp_payed_id__48': None, 'search_content__48': None, 'order_id__48': 322291, 'ps_response_date__48': None, 'reason_marked__48': None, 'external_order__48': 'N', 'store_id__48': None, 'date_allow_delivery__48': None, 'marked__48': 'N', 'bx_user_id__48': 'c25d82068abec5df82bfb723bc95edae', 'running__48': 'N', 'user_id__48': 139357, 'order_topic__48': None, 'date_canceled__48': None, 'locked_by__48': None, 'canceled__48': 'N', 'emp_marked_id__48': None}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
root 2023-12-25 12:29:49,202 INFO siteUpdateOrders(). Podkluchenie k base site i otptavka zaprosa.
paramiko.transport 2023-12-25 12:29:49,224 INFO Connected (version 2.0, client OpenSSH_7.4)
paramiko.transport 2023-12-25 12:29:49,605 INFO Authentication (password) successful!
root 2023-12-25 12:29:53,549 INFO siteUpdateOrders(). Uspeshnoe poluchenie dannih.
root 2023-12-25 12:29:53,552 INFO site.dataSiteToBd(). Zapis dataframe v tablitsu site_update_order_new.
root 2023-12-25 12:29:53,723 ERROR site.dataSiteToBd(). Oshibka zapisi dannih v tab site_update_order_new - (psycopg2.errors.StringDataRightTruncation) value too long for type character(1)

[SQL: INSERT INTO public.site_update_order_new (order_id, user_id, status_id, account_number, additional_info, affiliate_id, allow_delivery, bx_user_id, canceled, comments, company_id, created_by, currency, date_allow_delivery, date_bill, date_canceled, da ... 98329 characters truncated ... (updated_1c__58)s, %(user_description__58)s, %(version__58)s, %(version_1c__58)s, %(promocode__58)s)]
[parameters: {'price_delivery__0': Decimal('0.0000'), 'pay_voucher_date__0': None, 'recurring_id__0': None, 'date_deducted__0': None, 'is_recurring__0': 'N', 'delivery_doc_num__0': None, 'status_id__0': 'NN', 'allow_delivery__0': 'N', 'reason_undo_deducted__0': None, 'comments__0': '¹# new_IM-12319951 ,?, ð/ñ', 'reserved__0': 'N', 'payed__0': 'N', 'user_description__0': None, 'is_sync_b24__0': 'N', 'ps_status_code__0': None, 'delivery_doc_date__0': None, 'promocode__0': None, 'ps_status_description__0': None, 'tracking_number__0': None, 'delivery_id__0': '24', 'sum_paid__0': Decimal('0.00'), 'date_bill__0': None, 'price__0': Decimal('29097.0000'), 'updated_1c__0': 'Y', 'date_insert__0': datetime.datetime(2023, 12, 5, 2, 21, 30), 'recount_flag__0': 'Y', 'ps_status__0': None, 'discount_value__0': Decimal('0.0000'), 'ps_sum__0': None, 'account_number__0': 'IM-12319951', 'responsible_id__0': None, 'date_payed__0': None, 'pay_system_id__0': 1, 'date_marked__0': None, 'date_status__0': datetime.datetime(2023, 12, 8, 14, 27, 24), 'person_type_id__0': 1, 'additional_info__0': None, 'stat_gid__0': 'BITRIX_SM.NTIxMjc1Ny41NjM4ODEuUlUuLi5zMQ==', 'tax_value__0': Decimal('0.00'), 'date_lock__0': None, 'emp_deducted_id__0': None, 'company_id__0': 0, 'affiliate_id__0': None, 'ps_status_message__0': None, 'price_payment__0': Decimal('0.0000'), 'created_by__0': 110499, 'reason_canceled__0': None, 'version_1c__0': None, 'ps_currency__0': None, 'date_update__0': datetime.datetime(2023, 12, 24, 20, 23, 42) ... 4443 parameters truncated ... 'discount_value__58': Decimal('0.0000'), 'ps_sum__58': None, 'account_number__58': 'IM-12322290', 'responsible_id__58': None, 'date_payed__58': None, 'pay_system_id__58': 1, 'date_marked__58': None, 'date_status__58': datetime.datetime(2023, 12, 24, 23, 50, 36), 'person_type_id__58': 1, 'additional_info__58': None, 'stat_gid__58': 'BITRIX_SM.NTU1ODYyNi4yNDEwMDAwLlJVLi4uczE=', 'tax_value__58': Decimal('0.00'), 'date_lock__58': None, 'emp_deducted_id__58': None, 'company_id__58': 0, 'affiliate_id__58': None, 'ps_status_message__58': None, 'price_payment__58': Decimal('0.0000'), 'created_by__58': 140181, 'reason_canceled__58': None, 'version_1c__58': None, 'ps_currency__58': None, 'date_update__58': datetime.datetime(2023, 12, 24, 23, 50, 38), 'emp_status_id__58': 4, 'date_pay_before__58': None, 'version__58': 53, 'emp_canceled_id__58': None, 'emp_allow_delivery_id__58': None, 'pay_voucher_num__58': None, 'currency__58': 'RUB', 'lid__58': 's1', 'id_1c__58': '325589', 'deducted__58': 'N', 'emp_payed_id__58': None, 'search_content__58': None, 'order_id__58': 322290, 'ps_response_date__58': None, 'reason_marked__58': None, 'external_order__58': 'N', 'store_id__58': None, 'date_allow_delivery__58': None, 'marked__58': 'N', 'bx_user_id__58': '29c163ce2aa9aad6dc00605348a96d96', 'running__58': 'N', 'user_id__58': 140181, 'order_topic__58': None, 'date_canceled__58': None, 'locked_by__58': None, 'canceled__58': 'N', 'emp_marked_id__58': None}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
Traceback (most recent call last):
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 2112, in _exec_insertmany_context
    dialect.do_execute(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.StringDataRightTruncation: value too long for type character(1)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "g:\py.projects\tb\data_collection\site_dat\load_data_site.py", line 95, in dataSiteToBd
    df.to_sql(tableName, engine_pg, schema='public', if_exists='append', index=False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\core\generic.py", line 3008, in to_sql
    return sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1958, in to_sql
    total_inserted = sql_engine.insert_records(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1507, in insert_records
    raise err
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1498, in insert_records
    return table.insert(chunksize=chunksize, method=method)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1059, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 951, in _execute_insert
    result = conn.execute(self.table.insert(), data)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\sql\elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1639, in _execute_clauseelement
    ret = self._execute_context(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1843, in _execute_context
    return self._exec_insertmany_context(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 2120, in _exec_insertmany_context
    self._handle_dbapi_exception(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 2343, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 2112, in _exec_insertmany_context
    dialect.do_execute(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError: (psycopg2.errors.StringDataRightTruncation) value too long for type character(1)

[SQL: INSERT INTO public.site_update_order_new (order_id, user_id, status_id, account_number, additional_info, affiliate_id, allow_delivery, bx_user_id, canceled, comments, company_id, created_by, currency, date_allow_delivery, date_bill, date_canceled, da ... 98329 characters truncated ... (updated_1c__58)s, %(user_description__58)s, %(version__58)s, %(version_1c__58)s, %(promocode__58)s)]
[parameters: {'price_delivery__0': Decimal('0.0000'), 'pay_voucher_date__0': None, 'recurring_id__0': None, 'date_deducted__0': None, 'is_recurring__0': 'N', 'delivery_doc_num__0': None, 'status_id__0': 'NN', 'allow_delivery__0': 'N', 'reason_undo_deducted__0': None, 'comments__0': '¹# new_IM-12319951 ,?, ð/ñ', 'reserved__0': 'N', 'payed__0': 'N', 'user_description__0': None, 'is_sync_b24__0': 'N', 'ps_status_code__0': None, 'delivery_doc_date__0': None, 'promocode__0': None, 'ps_status_description__0': None, 'tracking_number__0': None, 'delivery_id__0': '24', 'sum_paid__0': Decimal('0.00'), 'date_bill__0': None, 'price__0': Decimal('29097.0000'), 'updated_1c__0': 'Y', 'date_insert__0': datetime.datetime(2023, 12, 5, 2, 21, 30), 'recount_flag__0': 'Y', 'ps_status__0': None, 'discount_value__0': Decimal('0.0000'), 'ps_sum__0': None, 'account_number__0': 'IM-12319951', 'responsible_id__0': None, 'date_payed__0': None, 'pay_system_id__0': 1, 'date_marked__0': None, 'date_status__0': datetime.datetime(2023, 12, 8, 14, 27, 24), 'person_type_id__0': 1, 'additional_info__0': None, 'stat_gid__0': 'BITRIX_SM.NTIxMjc1Ny41NjM4ODEuUlUuLi5zMQ==', 'tax_value__0': Decimal('0.00'), 'date_lock__0': None, 'emp_deducted_id__0': None, 'company_id__0': 0, 'affiliate_id__0': None, 'ps_status_message__0': None, 'price_payment__0': Decimal('0.0000'), 'created_by__0': 110499, 'reason_canceled__0': None, 'version_1c__0': None, 'ps_currency__0': None, 'date_update__0': datetime.datetime(2023, 12, 24, 20, 23, 42) ... 4443 parameters truncated ... 'discount_value__58': Decimal('0.0000'), 'ps_sum__58': None, 'account_number__58': 'IM-12322290', 'responsible_id__58': None, 'date_payed__58': None, 'pay_system_id__58': 1, 'date_marked__58': None, 'date_status__58': datetime.datetime(2023, 12, 24, 23, 50, 36), 'person_type_id__58': 1, 'additional_info__58': None, 'stat_gid__58': 'BITRIX_SM.NTU1ODYyNi4yNDEwMDAwLlJVLi4uczE=', 'tax_value__58': Decimal('0.00'), 'date_lock__58': None, 'emp_deducted_id__58': None, 'company_id__58': 0, 'affiliate_id__58': None, 'ps_status_message__58': None, 'price_payment__58': Decimal('0.0000'), 'created_by__58': 140181, 'reason_canceled__58': None, 'version_1c__58': None, 'ps_currency__58': None, 'date_update__58': datetime.datetime(2023, 12, 24, 23, 50, 38), 'emp_status_id__58': 4, 'date_pay_before__58': None, 'version__58': 53, 'emp_canceled_id__58': None, 'emp_allow_delivery_id__58': None, 'pay_voucher_num__58': None, 'currency__58': 'RUB', 'lid__58': 's1', 'id_1c__58': '325589', 'deducted__58': 'N', 'emp_payed_id__58': None, 'search_content__58': None, 'order_id__58': 322290, 'ps_response_date__58': None, 'reason_marked__58': None, 'external_order__58': 'N', 'store_id__58': None, 'date_allow_delivery__58': None, 'marked__58': 'N', 'bx_user_id__58': '29c163ce2aa9aad6dc00605348a96d96', 'running__58': 'N', 'user_id__58': 140181, 'order_topic__58': None, 'date_canceled__58': None, 'locked_by__58': None, 'canceled__58': 'N', 'emp_marked_id__58': None}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
root 2023-12-25 12:29:53,725 INFO siteUsers(). Podkluchenie k base site i otptavka zaprosa.
paramiko.transport 2023-12-25 12:29:53,754 INFO Connected (version 2.0, client OpenSSH_7.4)
paramiko.transport 2023-12-25 12:29:54,225 INFO Authentication (password) successful!
root 2023-12-25 12:29:55,227 INFO siteUsers(). Uspeshnoe poluchenie dannih.
root 2023-12-25 12:29:55,230 INFO site.dataSiteToBd(). Zapis dataframe v tablitsu site_user_new.
root 2023-12-25 12:29:55,332 ERROR site.dataSiteToBd(). Oshibka zapisi dannih v tab site_user_new - (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "site_user_new_pkey"
DETAIL:  Key (id)=(141525) already exists.

[SQL: INSERT INTO public.site_user_new (id, date_register, timestamp_x, active, admin_notes, auto_time_zone, blocked, bx_user_id, checkword, checkword_time, confirm_code, email, external_auth_id, language_id, last_activity_date, last_login, name, last_name ... 11963 characters truncated ... __8)s, %(work_profile__8)s, %(work_state__8)s, %(work_street__8)s, %(work_www__8)s, %(work_zip__8)s)]
[parameters: {'checkword_time__0': datetime.datetime(2023, 12, 24, 3, 50, 1), 'work_notes__0': None, 'stored_hash__0': None, 'personal_street__0': None, 'admin_notes__0': None, 'personal_photo__0': None, 'work_phone__0': None, 'personal_gender__0': None, 'login_attempts__0': 0, 'personal_country__0': None, 'language_id__0': 'ru', 'last_login__0': datetime.datetime(2023, 12, 24, 3, 48, 26), 'personal_profession__0': None, 'work_fax__0': None, 'personal_icq__0': None, 'time_zone_offset__0': None, 'name__0': 'Íàòàëüÿ', 'work_company__0': None, 'password_expired__0': 'N', 'work_logo__0': None, 'personal_zip__0': None, 'title__0': None, 'personal_birthday__0': None, 'personal_mailbox__0': None, 'timestamp_x__0': datetime.datetime(2023, 12, 24, 3, 50, 6), 'personal_phone__0': None, 'auto_time_zone__0': None, 'bx_user_id__0': '3ecefb290c7f0d4118d0c226228a63a5', 'login__0': 'natascha7878@mail.ru', 'personal_state__0': None, 'work_profile__0': None, 'work_zip__0': None, 'work_country__0': None, 'work_city__0': None, 'work_department__0': None, 'personal_mobile__0': '+7 (919) 551-95-63', 'personal_city__0': 'Íîÿáðüñê', 'checkword__0': '$6$GXxV40eqhPsA26Fe$vDEX4vemc3OEsJxheH0ieT.7HJuadg9Xq/Z4qneK9ErRIQWHXTJAtKHHT2/mcutzTuE3PcqRQ8wumuAHLvNRE0', 'password__0': '$6$ci6ExLdNbUNn14y4$c.ciDu5P/0AxH/O7bcxkw.1xV5VJEQvIUqqK/fynvNli2tFro0byoX.g2Q6WeK4V1Fpa1MDKqXFR9hjWpUYmG.', 'active__0': 'Y', 'personal_fax__0': None, 'personal_notes__0': None, 'work_pager__0': None, 'personal_birthdate__0': None, 'date_register__0': datetime.datetime(2023, 12, 24, 3, 48, 25), 'second_name__0': None, 'blocked__0': 'N', 'work_mailbox__0': None, 'work_position__0': None, 'work_www__0': None ... 458 parameters truncated ... 'personal_profession__8': None, 'work_fax__8': None, 'personal_icq__8': None, 'time_zone_offset__8': None, 'name__8': 'Îëüãà', 'work_company__8': None, 'password_expired__8': 'N', 'work_logo__8': None, 'personal_zip__8': None, 'title__8': None, 'personal_birthday__8': None, 'personal_mailbox__8': None, 'timestamp_x__8': None, 'personal_phone__8': None, 'auto_time_zone__8': None, 'bx_user_id__8': '513fa582b151cf38078e1d8cee5566d0', 'login__8': 'olga.ignatjeva123@gmail.com', 'personal_state__8': None, 'work_profile__8': None, 'work_zip__8': None, 'work_country__8': None, 'work_city__8': None, 'work_department__8': None, 'personal_mobile__8': '+7 (999) 228-59-06', 'personal_city__8': 'Èæåâñê', 'checkword__8': '$6$gFCavVYdOE7rgLLy$aQcwALZ3hrNPP2g5RYoo9LkTD7sGaVImPXYpRKkM3Hwi5bpjrsJWULS4taKp63XxIf5ISqfB5wXKFTiAZOktt/', 'password__8': '$6$0dXHtpiJSTnqhOes$T1.HMwuRuSfVCZvqR9OMa.vp4vLyZwbY9gAEbyO258OJlWl8Ii94PyFwhve0glrPlhBF3vTD7RVo1MfsIXnWU0', 'active__8': 'Y', 'personal_fax__8': None, 'personal_notes__8': None, 'work_pager__8': None, 'personal_birthdate__8': None, 'date_register__8': datetime.datetime(2023, 12, 24, 23, 45, 34), 'second_name__8': None, 'blocked__8': 'N', 'work_mailbox__8': None, 'work_position__8': None, 'work_www__8': None, 'external_auth_id__8': None, 'id__8': 141533, 'personal_www__8': None, 'time_zone__8': None, 'work_street__8': None, 'email__8': 'olga.ignatjeva123@gmail.com', 'work_state__8': None, 'confirm_code__8': None, 'last_name__8': 'Èãíàòüåâà', 'personal_pager__8': None, 'last_activity_date__8': None, 'lid__8': 's1'}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
Traceback (most recent call last):
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 2112, in _exec_insertmany_context
    dialect.do_execute(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "site_user_new_pkey"
DETAIL:  Key (id)=(141525) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "g:\py.projects\tb\data_collection\site_dat\load_data_site.py", line 95, in dataSiteToBd
    df.to_sql(tableName, engine_pg, schema='public', if_exists='append', index=False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\core\generic.py", line 3008, in to_sql
    return sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1958, in to_sql
    total_inserted = sql_engine.insert_records(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1507, in insert_records
    raise err
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1498, in insert_records
    return table.insert(chunksize=chunksize, method=method)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1059, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 951, in _execute_insert
    result = conn.execute(self.table.insert(), data)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\sql\elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1639, in _execute_clauseelement
    ret = self._execute_context(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1843, in _execute_context
    return self._exec_insertmany_context(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 2120, in _exec_insertmany_context
    self._handle_dbapi_exception(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 2343, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 2112, in _exec_insertmany_context
    dialect.do_execute(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "site_user_new_pkey"
DETAIL:  Key (id)=(141525) already exists.

[SQL: INSERT INTO public.site_user_new (id, date_register, timestamp_x, active, admin_notes, auto_time_zone, blocked, bx_user_id, checkword, checkword_time, confirm_code, email, external_auth_id, language_id, last_activity_date, last_login, name, last_name ... 11963 characters truncated ... __8)s, %(work_profile__8)s, %(work_state__8)s, %(work_street__8)s, %(work_www__8)s, %(work_zip__8)s)]
[parameters: {'checkword_time__0': datetime.datetime(2023, 12, 24, 3, 50, 1), 'work_notes__0': None, 'stored_hash__0': None, 'personal_street__0': None, 'admin_notes__0': None, 'personal_photo__0': None, 'work_phone__0': None, 'personal_gender__0': None, 'login_attempts__0': 0, 'personal_country__0': None, 'language_id__0': 'ru', 'last_login__0': datetime.datetime(2023, 12, 24, 3, 48, 26), 'personal_profession__0': None, 'work_fax__0': None, 'personal_icq__0': None, 'time_zone_offset__0': None, 'name__0': 'Íàòàëüÿ', 'work_company__0': None, 'password_expired__0': 'N', 'work_logo__0': None, 'personal_zip__0': None, 'title__0': None, 'personal_birthday__0': None, 'personal_mailbox__0': None, 'timestamp_x__0': datetime.datetime(2023, 12, 24, 3, 50, 6), 'personal_phone__0': None, 'auto_time_zone__0': None, 'bx_user_id__0': '3ecefb290c7f0d4118d0c226228a63a5', 'login__0': 'natascha7878@mail.ru', 'personal_state__0': None, 'work_profile__0': None, 'work_zip__0': None, 'work_country__0': None, 'work_city__0': None, 'work_department__0': None, 'personal_mobile__0': '+7 (919) 551-95-63', 'personal_city__0': 'Íîÿáðüñê', 'checkword__0': '$6$GXxV40eqhPsA26Fe$vDEX4vemc3OEsJxheH0ieT.7HJuadg9Xq/Z4qneK9ErRIQWHXTJAtKHHT2/mcutzTuE3PcqRQ8wumuAHLvNRE0', 'password__0': '$6$ci6ExLdNbUNn14y4$c.ciDu5P/0AxH/O7bcxkw.1xV5VJEQvIUqqK/fynvNli2tFro0byoX.g2Q6WeK4V1Fpa1MDKqXFR9hjWpUYmG.', 'active__0': 'Y', 'personal_fax__0': None, 'personal_notes__0': None, 'work_pager__0': None, 'personal_birthdate__0': None, 'date_register__0': datetime.datetime(2023, 12, 24, 3, 48, 25), 'second_name__0': None, 'blocked__0': 'N', 'work_mailbox__0': None, 'work_position__0': None, 'work_www__0': None ... 458 parameters truncated ... 'personal_profession__8': None, 'work_fax__8': None, 'personal_icq__8': None, 'time_zone_offset__8': None, 'name__8': 'Îëüãà', 'work_company__8': None, 'password_expired__8': 'N', 'work_logo__8': None, 'personal_zip__8': None, 'title__8': None, 'personal_birthday__8': None, 'personal_mailbox__8': None, 'timestamp_x__8': None, 'personal_phone__8': None, 'auto_time_zone__8': None, 'bx_user_id__8': '513fa582b151cf38078e1d8cee5566d0', 'login__8': 'olga.ignatjeva123@gmail.com', 'personal_state__8': None, 'work_profile__8': None, 'work_zip__8': None, 'work_country__8': None, 'work_city__8': None, 'work_department__8': None, 'personal_mobile__8': '+7 (999) 228-59-06', 'personal_city__8': 'Èæåâñê', 'checkword__8': '$6$gFCavVYdOE7rgLLy$aQcwALZ3hrNPP2g5RYoo9LkTD7sGaVImPXYpRKkM3Hwi5bpjrsJWULS4taKp63XxIf5ISqfB5wXKFTiAZOktt/', 'password__8': '$6$0dXHtpiJSTnqhOes$T1.HMwuRuSfVCZvqR9OMa.vp4vLyZwbY9gAEbyO258OJlWl8Ii94PyFwhve0glrPlhBF3vTD7RVo1MfsIXnWU0', 'active__8': 'Y', 'personal_fax__8': None, 'personal_notes__8': None, 'work_pager__8': None, 'personal_birthdate__8': None, 'date_register__8': datetime.datetime(2023, 12, 24, 23, 45, 34), 'second_name__8': None, 'blocked__8': 'N', 'work_mailbox__8': None, 'work_position__8': None, 'work_www__8': None, 'external_auth_id__8': None, 'id__8': 141533, 'personal_www__8': None, 'time_zone__8': None, 'work_street__8': None, 'email__8': 'olga.ignatjeva123@gmail.com', 'work_state__8': None, 'confirm_code__8': None, 'last_name__8': 'Èãíàòüåâà', 'personal_pager__8': None, 'last_activity_date__8': None, 'lid__8': 's1'}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
root 2023-12-25 12:29:55,333 INFO siteInsertBasket(). Podkluchenie k base site i otptavka zaprosa.
paramiko.transport 2023-12-25 12:29:55,361 INFO Connected (version 2.0, client OpenSSH_7.4)
paramiko.transport 2023-12-25 12:29:55,722 INFO Authentication (password) successful!
root 2023-12-25 12:29:59,098 INFO siteInsertBasket(). Uspeshnoe poluchenie dannih.
root 2023-12-25 12:29:59,100 INFO site.dataSiteToBd(). Zapis dataframe v tablitsu site_insert_basket_new.
root 2023-12-25 12:29:59,262 ERROR site.dataSiteToBd(). Oshibka zapisi dannih v tab site_insert_basket_new - (psycopg2.errors.StringDataRightTruncation) value too long for type character(1)

[SQL: INSERT INTO public.site_insert_basket_new (basket_id, order_id, fuser_id, barcode_multi, base_price, callback_func, can_buy, cancel_callback_func, catalog_xml_id, currency, custom_price, date_insert, date_refresh, date_update, deducted, delay, detail ... 603392 characters truncated ... 574)s, %(subscribe__574)s, %(type__574)s, %(vat_included__574)s, %(vat_rate__574)s, %(weight__574)s)]
[parameters: {'subscribe__0': 'N', 'deducted__0': 'N', 'weight__0': 0.0, 'set_parent_id__0': None, 'price__0': Decimal('2190.0000'), 'date_insert__0': datetime.datetime(2023, 12, 24, 0, 0, 6), 'measure_name__0': None, 'vat_included__0': 'Y', 'order_callback_func__0': None, 'module__0': 'catalog', 'order_id__0': 322167.0, 'name__0': 'Âûéäè èç òåíè (âàéò, íüþ) (50 ðàçìåð)', 'discount_coupon__0': None, 'basket_id__0': 3020480, 'recommendation__0': None, 'date_update__0': datetime.datetime(2023, 12, 24, 0, 0, 9), 'discount_price__0': Decimal('0.0000'), 'discount_value__0': None, 'product_id__0': 438071, 'pay_callback_func__0': None, 'price_type_id__0': None, 'quantity__0': 1.0, 'dimensions__0': None, 'reserved__0': 'N', 'catalog_xml_id__0': 'd54b6438-ee7e-44a0-82fd-86cdb3c9a1a1#', 'custom_price__0': 'Y', 'base_price__0': Decimal('2190.0000'), 'can_buy__0': 'Y', 'cancel_callback_func__0': None, 'vat_rate__0': Decimal('0.0000'), 'delay__0': 'N', 'callback_func__0': None, 'product_price_id__0': None, 'fuser_id__0': 56791715, 'measure_code__0': None, 'sort__0': 200, 'barcode_multi__0': 'N', 'marking_code_group__0': None, 'reserve_quantity__0': None, 'discount_name__0': None, 'detail_page_url__0': None, 'type__0': None, 'notes__0': None, 'currency__0': 'RUB', 'product_provider_class__0': 'CCatalogProductProvider', 'product_xml_id__0': '61647a8a-8da5-11ee-af9c-3cecefea1bc1#61647a90-8da5-11ee-af9c-3cecefea1bc1', 'date_refresh__0': None, 'lid__0': 's1', 'subscribe__1': 'N', 'deducted__1': 'N' ... 27500 parameters truncated ... 'date_refresh__573': None, 'lid__573': 's1', 'subscribe__574': 'N', 'deducted__574': 'N', 'weight__574': 0.0, 'set_parent_id__574': None, 'price__574': Decimal('990.0000'), 'date_insert__574': datetime.datetime(2023, 12, 24, 23, 58, 42), 'measure_name__574': 'øò', 'vat_included__574': 'N', 'order_callback_func__574': None, 'module__574': 'catalog', 'order_id__574': None, 'name__574': 'Èñêóññòâî êðàñîòû (ñ ðåìåøêîì) (48 ðàçìåð)', 'discount_coupon__574': None, 'basket_id__574': 3021169, 'recommendation__574': None, 'date_update__574': datetime.datetime(2023, 12, 25, 0, 11, 38), 'discount_price__574': Decimal('0.0000'), 'discount_value__574': None, 'product_id__574': 396655, 'pay_callback_func__574': None, 'price_type_id__574': 1.0, 'quantity__574': 1.0, 'dimensions__574': 's:50:"a:3:{s:5:"WIDTH";N;s:6:"HEIGHT";N;s:6:"LENGTH";N;}";', 'reserved__574': 'N', 'catalog_xml_id__574': 'd54b6438-ee7e-44a0-82fd-86cdb3c9a1a1#', 'custom_price__574': 'Y', 'base_price__574': Decimal('990.0000'), 'can_buy__574': 'Y', 'cancel_callback_func__574': None, 'vat_rate__574': None, 'delay__574': 'N', 'callback_func__574': None, 'product_price_id__574': 97879.0, 'fuser_id__574': 60910346, 'measure_code__574': 796.0, 'sort__574': 1800, 'barcode_multi__574': 'N', 'marking_code_group__574': None, 'reserve_quantity__574': None, 'discount_name__574': None, 'detail_page_url__574': None, 'type__574': None, 'notes__574': 'Áàçîâàÿ öåíà', 'currency__574': 'RUB', 'product_provider_class__574': 'CCatalogProductProvider', 'product_xml_id__574': 'f44ea4fe-66fa-11ed-a245-54bf646484f8#43f17feb-671d-11ed-a245-54bf646484f8', 'date_refresh__574': None, 'lid__574': 's1'}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
Traceback (most recent call last):
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 2112, in _exec_insertmany_context
    dialect.do_execute(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.StringDataRightTruncation: value too long for type character(1)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "g:\py.projects\tb\data_collection\site_dat\load_data_site.py", line 95, in dataSiteToBd
    df.to_sql(tableName, engine_pg, schema='public', if_exists='append', index=False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\core\generic.py", line 3008, in to_sql
    return sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1958, in to_sql
    total_inserted = sql_engine.insert_records(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1507, in insert_records
    raise err
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1498, in insert_records
    return table.insert(chunksize=chunksize, method=method)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1059, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 951, in _execute_insert
    result = conn.execute(self.table.insert(), data)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\sql\elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1639, in _execute_clauseelement
    ret = self._execute_context(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1843, in _execute_context
    return self._exec_insertmany_context(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 2120, in _exec_insertmany_context
    self._handle_dbapi_exception(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 2343, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 2112, in _exec_insertmany_context
    dialect.do_execute(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError: (psycopg2.errors.StringDataRightTruncation) value too long for type character(1)

[SQL: INSERT INTO public.site_insert_basket_new (basket_id, order_id, fuser_id, barcode_multi, base_price, callback_func, can_buy, cancel_callback_func, catalog_xml_id, currency, custom_price, date_insert, date_refresh, date_update, deducted, delay, detail ... 603392 characters truncated ... 574)s, %(subscribe__574)s, %(type__574)s, %(vat_included__574)s, %(vat_rate__574)s, %(weight__574)s)]
[parameters: {'subscribe__0': 'N', 'deducted__0': 'N', 'weight__0': 0.0, 'set_parent_id__0': None, 'price__0': Decimal('2190.0000'), 'date_insert__0': datetime.datetime(2023, 12, 24, 0, 0, 6), 'measure_name__0': None, 'vat_included__0': 'Y', 'order_callback_func__0': None, 'module__0': 'catalog', 'order_id__0': 322167.0, 'name__0': 'Âûéäè èç òåíè (âàéò, íüþ) (50 ðàçìåð)', 'discount_coupon__0': None, 'basket_id__0': 3020480, 'recommendation__0': None, 'date_update__0': datetime.datetime(2023, 12, 24, 0, 0, 9), 'discount_price__0': Decimal('0.0000'), 'discount_value__0': None, 'product_id__0': 438071, 'pay_callback_func__0': None, 'price_type_id__0': None, 'quantity__0': 1.0, 'dimensions__0': None, 'reserved__0': 'N', 'catalog_xml_id__0': 'd54b6438-ee7e-44a0-82fd-86cdb3c9a1a1#', 'custom_price__0': 'Y', 'base_price__0': Decimal('2190.0000'), 'can_buy__0': 'Y', 'cancel_callback_func__0': None, 'vat_rate__0': Decimal('0.0000'), 'delay__0': 'N', 'callback_func__0': None, 'product_price_id__0': None, 'fuser_id__0': 56791715, 'measure_code__0': None, 'sort__0': 200, 'barcode_multi__0': 'N', 'marking_code_group__0': None, 'reserve_quantity__0': None, 'discount_name__0': None, 'detail_page_url__0': None, 'type__0': None, 'notes__0': None, 'currency__0': 'RUB', 'product_provider_class__0': 'CCatalogProductProvider', 'product_xml_id__0': '61647a8a-8da5-11ee-af9c-3cecefea1bc1#61647a90-8da5-11ee-af9c-3cecefea1bc1', 'date_refresh__0': None, 'lid__0': 's1', 'subscribe__1': 'N', 'deducted__1': 'N' ... 27500 parameters truncated ... 'date_refresh__573': None, 'lid__573': 's1', 'subscribe__574': 'N', 'deducted__574': 'N', 'weight__574': 0.0, 'set_parent_id__574': None, 'price__574': Decimal('990.0000'), 'date_insert__574': datetime.datetime(2023, 12, 24, 23, 58, 42), 'measure_name__574': 'øò', 'vat_included__574': 'N', 'order_callback_func__574': None, 'module__574': 'catalog', 'order_id__574': None, 'name__574': 'Èñêóññòâî êðàñîòû (ñ ðåìåøêîì) (48 ðàçìåð)', 'discount_coupon__574': None, 'basket_id__574': 3021169, 'recommendation__574': None, 'date_update__574': datetime.datetime(2023, 12, 25, 0, 11, 38), 'discount_price__574': Decimal('0.0000'), 'discount_value__574': None, 'product_id__574': 396655, 'pay_callback_func__574': None, 'price_type_id__574': 1.0, 'quantity__574': 1.0, 'dimensions__574': 's:50:"a:3:{s:5:"WIDTH";N;s:6:"HEIGHT";N;s:6:"LENGTH";N;}";', 'reserved__574': 'N', 'catalog_xml_id__574': 'd54b6438-ee7e-44a0-82fd-86cdb3c9a1a1#', 'custom_price__574': 'Y', 'base_price__574': Decimal('990.0000'), 'can_buy__574': 'Y', 'cancel_callback_func__574': None, 'vat_rate__574': None, 'delay__574': 'N', 'callback_func__574': None, 'product_price_id__574': 97879.0, 'fuser_id__574': 60910346, 'measure_code__574': 796.0, 'sort__574': 1800, 'barcode_multi__574': 'N', 'marking_code_group__574': None, 'reserve_quantity__574': None, 'discount_name__574': None, 'detail_page_url__574': None, 'type__574': None, 'notes__574': 'Áàçîâàÿ öåíà', 'currency__574': 'RUB', 'product_provider_class__574': 'CCatalogProductProvider', 'product_xml_id__574': 'f44ea4fe-66fa-11ed-a245-54bf646484f8#43f17feb-671d-11ed-a245-54bf646484f8', 'date_refresh__574': None, 'lid__574': 's1'}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
root 2023-12-25 12:29:59,265 INFO siteUpdateBasket(). Podkluchenie k base site i otptavka zaprosa.
paramiko.transport 2023-12-25 12:29:59,291 INFO Connected (version 2.0, client OpenSSH_7.4)
paramiko.transport 2023-12-25 12:29:59,640 INFO Authentication (password) successful!
root 2023-12-25 12:30:03,203 INFO siteUpdateBasket(). Uspeshnoe poluchenie dannih.
root 2023-12-25 12:30:03,214 INFO site.dataSiteToBd(). Zapis dataframe v tablitsu site_update_basket_new.
root 2023-12-25 12:30:03,429 ERROR site.dataSiteToBd(). Oshibka zapisi dannih v tab site_update_basket_new - (psycopg2.errors.StringDataRightTruncation) value too long for type character(1)

[SQL: INSERT INTO public.site_update_basket_new (basket_id, order_id, fuser_id, barcode_multi, base_price, callback_func, can_buy, cancel_callback_func, catalog_xml_id, currency, custom_price, date_insert, date_refresh, date_update, deducted, delay, detail ... 715540 characters truncated ... 680)s, %(subscribe__680)s, %(type__680)s, %(vat_included__680)s, %(vat_rate__680)s, %(weight__680)s)]
[parameters: {'subscribe__0': 'N', 'deducted__0': 'N', 'weight__0': 0.0, 'set_parent_id__0': None, 'price__0': Decimal('1190.0000'), 'date_insert__0': datetime.datetime(2022, 11, 26, 10, 7, 49), 'measure_name__0': 'øò', 'vat_included__0': 'N', 'order_callback_func__0': None, 'module__0': 'catalog', 'order_id__0': 274499.0, 'name__0': 'Ñêðîìíîå îáàÿíèå (àìåòèñò) (50 ðàçìåð)', 'discount_coupon__0': None, 'basket_id__0': 2448330, 'recommendation__0': None, 'date_update__0': datetime.datetime(2023, 12, 24, 14, 55, 7), 'discount_price__0': Decimal('0.0000'), 'discount_value__0': None, 'product_id__0': 384925, 'pay_callback_func__0': None, 'price_type_id__0': 1.0, 'quantity__0': 1.0, 'dimensions__0': 's:50:"a:3:{s:5:"WIDTH";N;s:6:"HEIGHT";N;s:6:"LENGTH";N;}";', 'reserved__0': 'N', 'catalog_xml_id__0': 'd54b6438-ee7e-44a0-82fd-86cdb3c9a1a1#', 'custom_price__0': 'Y', 'base_price__0': Decimal('1190.0000'), 'can_buy__0': 'Y', 'cancel_callback_func__0': None, 'vat_rate__0': None, 'delay__0': 'N', 'callback_func__0': None, 'product_price_id__0': 93880.0, 'fuser_id__0': 46580098, 'measure_code__0': 796.0, 'sort__0': 200, 'barcode_multi__0': 'N', 'marking_code_group__0': None, 'reserve_quantity__0': None, 'discount_name__0': None, 'detail_page_url__0': None, 'type__0': None, 'notes__0': 'Áàçîâàÿ öåíà', 'currency__0': 'RUB', 'product_provider_class__0': 'CCatalogProductProvider', 'product_xml_id__0': '57a78155-3b0d-11ed-a244-54bf646484f8#57a7815b-3b0d-11ed-a244-54bf646484f8', 'date_refresh__0': None, 'lid__0': 's1', 'subscribe__1': 'N', 'deducted__1': 'N' ... 32588 parameters truncated ... 'date_refresh__679': None, 'lid__679': 's1', 'subscribe__680': 'N', 'deducted__680': 'N', 'weight__680': 0.0, 'set_parent_id__680': None, 'price__680': Decimal('1690.0000'), 'date_insert__680': datetime.datetime(2023, 12, 11, 0, 17, 26), 'measure_name__680': 'øò', 'vat_included__680': 'N', 'order_callback_func__680': None, 'module__680': 'catalog', 'order_id__680': None, 'name__680': 'Ïîêîðèòü âåñü ìèð (ëåäè) (52 ðàçìåð)', 'discount_coupon__680': None, 'basket_id__680': 3006783, 'recommendation__680': None, 'date_update__680': datetime.datetime(2023, 12, 24, 12, 8, 56), 'discount_price__680': Decimal('0.0000'), 'discount_value__680': None, 'product_id__680': 429796, 'pay_callback_func__680': None, 'price_type_id__680': 1.0, 'quantity__680': 1.0, 'dimensions__680': 's:50:"a:3:{s:5:"WIDTH";N;s:6:"HEIGHT";N;s:6:"LENGTH";N;}";', 'reserved__680': 'N', 'catalog_xml_id__680': 'd54b6438-ee7e-44a0-82fd-86cdb3c9a1a1#', 'custom_price__680': 'Y', 'base_price__680': Decimal('1690.0000'), 'can_buy__680': 'Y', 'cancel_callback_func__680': None, 'vat_rate__680': None, 'delay__680': 'N', 'callback_func__680': None, 'product_price_id__680': 114301.0, 'fuser_id__680': 61797161, 'measure_code__680': 796.0, 'sort__680': 1400, 'barcode_multi__680': 'N', 'marking_code_group__680': None, 'reserve_quantity__680': None, 'discount_name__680': None, 'detail_page_url__680': None, 'type__680': None, 'notes__680': 'Áàçîâàÿ öåíà', 'currency__680': 'RUB', 'product_provider_class__680': 'CCatalogProductProvider', 'product_xml_id__680': 'c20b254a-503e-11ee-af97-3cecefea1bc1#c20b254f-503e-11ee-af97-3cecefea1bc1', 'date_refresh__680': None, 'lid__680': 's1'}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
Traceback (most recent call last):
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 2112, in _exec_insertmany_context
    dialect.do_execute(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.StringDataRightTruncation: value too long for type character(1)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "g:\py.projects\tb\data_collection\site_dat\load_data_site.py", line 95, in dataSiteToBd
    df.to_sql(tableName, engine_pg, schema='public', if_exists='append', index=False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\core\generic.py", line 3008, in to_sql
    return sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1958, in to_sql
    total_inserted = sql_engine.insert_records(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1507, in insert_records
    raise err
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1498, in insert_records
    return table.insert(chunksize=chunksize, method=method)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1059, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 951, in _execute_insert
    result = conn.execute(self.table.insert(), data)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\sql\elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1639, in _execute_clauseelement
    ret = self._execute_context(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1843, in _execute_context
    return self._exec_insertmany_context(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 2120, in _exec_insertmany_context
    self._handle_dbapi_exception(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 2343, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 2112, in _exec_insertmany_context
    dialect.do_execute(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError: (psycopg2.errors.StringDataRightTruncation) value too long for type character(1)

[SQL: INSERT INTO public.site_update_basket_new (basket_id, order_id, fuser_id, barcode_multi, base_price, callback_func, can_buy, cancel_callback_func, catalog_xml_id, currency, custom_price, date_insert, date_refresh, date_update, deducted, delay, detail ... 715540 characters truncated ... 680)s, %(subscribe__680)s, %(type__680)s, %(vat_included__680)s, %(vat_rate__680)s, %(weight__680)s)]
[parameters: {'subscribe__0': 'N', 'deducted__0': 'N', 'weight__0': 0.0, 'set_parent_id__0': None, 'price__0': Decimal('1190.0000'), 'date_insert__0': datetime.datetime(2022, 11, 26, 10, 7, 49), 'measure_name__0': 'øò', 'vat_included__0': 'N', 'order_callback_func__0': None, 'module__0': 'catalog', 'order_id__0': 274499.0, 'name__0': 'Ñêðîìíîå îáàÿíèå (àìåòèñò) (50 ðàçìåð)', 'discount_coupon__0': None, 'basket_id__0': 2448330, 'recommendation__0': None, 'date_update__0': datetime.datetime(2023, 12, 24, 14, 55, 7), 'discount_price__0': Decimal('0.0000'), 'discount_value__0': None, 'product_id__0': 384925, 'pay_callback_func__0': None, 'price_type_id__0': 1.0, 'quantity__0': 1.0, 'dimensions__0': 's:50:"a:3:{s:5:"WIDTH";N;s:6:"HEIGHT";N;s:6:"LENGTH";N;}";', 'reserved__0': 'N', 'catalog_xml_id__0': 'd54b6438-ee7e-44a0-82fd-86cdb3c9a1a1#', 'custom_price__0': 'Y', 'base_price__0': Decimal('1190.0000'), 'can_buy__0': 'Y', 'cancel_callback_func__0': None, 'vat_rate__0': None, 'delay__0': 'N', 'callback_func__0': None, 'product_price_id__0': 93880.0, 'fuser_id__0': 46580098, 'measure_code__0': 796.0, 'sort__0': 200, 'barcode_multi__0': 'N', 'marking_code_group__0': None, 'reserve_quantity__0': None, 'discount_name__0': None, 'detail_page_url__0': None, 'type__0': None, 'notes__0': 'Áàçîâàÿ öåíà', 'currency__0': 'RUB', 'product_provider_class__0': 'CCatalogProductProvider', 'product_xml_id__0': '57a78155-3b0d-11ed-a244-54bf646484f8#57a7815b-3b0d-11ed-a244-54bf646484f8', 'date_refresh__0': None, 'lid__0': 's1', 'subscribe__1': 'N', 'deducted__1': 'N' ... 32588 parameters truncated ... 'date_refresh__679': None, 'lid__679': 's1', 'subscribe__680': 'N', 'deducted__680': 'N', 'weight__680': 0.0, 'set_parent_id__680': None, 'price__680': Decimal('1690.0000'), 'date_insert__680': datetime.datetime(2023, 12, 11, 0, 17, 26), 'measure_name__680': 'øò', 'vat_included__680': 'N', 'order_callback_func__680': None, 'module__680': 'catalog', 'order_id__680': None, 'name__680': 'Ïîêîðèòü âåñü ìèð (ëåäè) (52 ðàçìåð)', 'discount_coupon__680': None, 'basket_id__680': 3006783, 'recommendation__680': None, 'date_update__680': datetime.datetime(2023, 12, 24, 12, 8, 56), 'discount_price__680': Decimal('0.0000'), 'discount_value__680': None, 'product_id__680': 429796, 'pay_callback_func__680': None, 'price_type_id__680': 1.0, 'quantity__680': 1.0, 'dimensions__680': 's:50:"a:3:{s:5:"WIDTH";N;s:6:"HEIGHT";N;s:6:"LENGTH";N;}";', 'reserved__680': 'N', 'catalog_xml_id__680': 'd54b6438-ee7e-44a0-82fd-86cdb3c9a1a1#', 'custom_price__680': 'Y', 'base_price__680': Decimal('1690.0000'), 'can_buy__680': 'Y', 'cancel_callback_func__680': None, 'vat_rate__680': None, 'delay__680': 'N', 'callback_func__680': None, 'product_price_id__680': 114301.0, 'fuser_id__680': 61797161, 'measure_code__680': 796.0, 'sort__680': 1400, 'barcode_multi__680': 'N', 'marking_code_group__680': None, 'reserve_quantity__680': None, 'discount_name__680': None, 'detail_page_url__680': None, 'type__680': None, 'notes__680': 'Áàçîâàÿ öåíà', 'currency__680': 'RUB', 'product_provider_class__680': 'CCatalogProductProvider', 'product_xml_id__680': 'c20b254a-503e-11ee-af97-3cecefea1bc1#c20b254f-503e-11ee-af97-3cecefea1bc1', 'date_refresh__680': None, 'lid__680': 's1'}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
root 2023-12-25 12:30:03,433 INFO siteInsertFuser(). Podkluchenie k base site i otptavka zaprosa.
paramiko.transport 2023-12-25 12:30:03,459 INFO Connected (version 2.0, client OpenSSH_7.4)
paramiko.transport 2023-12-25 12:30:03,829 INFO Authentication (password) successful!
root 2023-12-25 12:30:04,994 INFO siteInsertFuser(). Uspeshnoe poluchenie dannih.
root 2023-12-25 12:30:04,997 INFO site.dataSiteToBd(). Zapis dataframe v tablitsu site_insert_fuser_new.
root 2023-12-25 12:30:05,131 ERROR site.dataSiteToBd(). Oshibka zapisi dannih v tab site_insert_fuser_new - (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "site_insert_fuser_new_fuser_id_key"
DETAIL:  Key (fuser_id)=(62513845) already exists.

[SQL: INSERT INTO public.site_insert_fuser_new (fuser_id, date_insert, date_update, user_id, code) VALUES (%(fuser_id__0)s, %(date_insert__0)s, %(date_update__0)s, %(user_id__0)s, %(code__0)s), (%(fuser_id__1)s, %(date_insert__1)s, %(date_update__1)s, %(us ... 97198 characters truncated ... s), (%(fuser_id__999)s, %(date_insert__999)s, %(date_update__999)s, %(user_id__999)s, %(code__999)s)]
[parameters: {'user_id__0': None, 'code__0': 'd81e7090d18155286b91689dcc1a1998', 'date_insert__0': datetime.datetime(2023, 12, 24, 0, 0, 3), 'date_update__0': datetime.datetime(2023, 12, 24, 0, 0, 3), 'fuser_id__0': 62513845, 'user_id__1': None, 'code__1': 'de426c0156877e94d5218a461aff2efe', 'date_insert__1': datetime.datetime(2023, 12, 24, 0, 0, 3), 'date_update__1': datetime.datetime(2023, 12, 24, 0, 0, 3), 'fuser_id__1': 62513846, 'user_id__2': None, 'code__2': '347473677c13e2a5a948d7580fb21245', 'date_insert__2': datetime.datetime(2023, 12, 24, 0, 0, 4), 'date_update__2': datetime.datetime(2023, 12, 24, 0, 0, 4), 'fuser_id__2': 62513847, 'user_id__3': None, 'code__3': '6dd35bd1438ad4ecfa54f491e3f2a06f', 'date_insert__3': datetime.datetime(2023, 12, 24, 0, 0, 21), 'date_update__3': datetime.datetime(2023, 12, 24, 0, 0, 21), 'fuser_id__3': 62513848, 'user_id__4': None, 'code__4': 'd30272576af30843e1645f3aed6cec56', 'date_insert__4': datetime.datetime(2023, 12, 24, 0, 0, 21), 'date_update__4': datetime.datetime(2023, 12, 24, 0, 0, 21), 'fuser_id__4': 62513849, 'user_id__5': None, 'code__5': '081e28e2d8c9ba3d80820f401b729fb8', 'date_insert__5': datetime.datetime(2023, 12, 24, 0, 0, 21), 'date_update__5': datetime.datetime(2023, 12, 24, 0, 0, 21), 'fuser_id__5': 62513850, 'user_id__6': None, 'code__6': '41ac659d356e3edfc6cccde3368a6113', 'date_insert__6': datetime.datetime(2023, 12, 24, 0, 0, 32), 'date_update__6': datetime.datetime(2023, 12, 25, 9, 6, 58), 'fuser_id__6': 62513851, 'user_id__7': None, 'code__7': '21a0ef33528ec46912b61101d81e6476', 'date_insert__7': datetime.datetime(2023, 12, 24, 0, 0, 57), 'date_update__7': datetime.datetime(2023, 12, 24, 0, 0, 57), 'fuser_id__7': 62513852, 'user_id__8': None, 'code__8': '36f7b02d82ca598592c68b0507a7f219', 'date_insert__8': datetime.datetime(2023, 12, 24, 0, 1, 11), 'date_update__8': datetime.datetime(2023, 12, 24, 0, 1, 11), 'fuser_id__8': 62513853, 'user_id__9': None, 'code__9': '0467a2e45b19268044fc85f5b51797ba', 'date_insert__9': datetime.datetime(2023, 12, 24, 0, 1, 11), 'date_update__9': datetime.datetime(2023, 12, 24, 0, 1, 11), 'fuser_id__9': 62513854 ... 4900 parameters truncated ... 'user_id__990': None, 'code__990': 'c061c96b6870ad4b74707108c4d8cefd', 'date_insert__990': datetime.datetime(2023, 12, 24, 1, 20, 18), 'date_update__990': datetime.datetime(2023, 12, 24, 1, 20, 18), 'fuser_id__990': 62514837, 'user_id__991': None, 'code__991': 'ee744405132c456c88e9c65fbf565ff2', 'date_insert__991': datetime.datetime(2023, 12, 24, 1, 20, 25), 'date_update__991': datetime.datetime(2023, 12, 24, 12, 26, 44), 'fuser_id__991': 62514838, 'user_id__992': None, 'code__992': '87d3072b24639b0e349925ae824080fa', 'date_insert__992': datetime.datetime(2023, 12, 24, 1, 20, 53), 'date_update__992': datetime.datetime(2023, 12, 24, 1, 20, 53), 'fuser_id__992': 62514839, 'user_id__993': None, 'code__993': '14d17beba1e3515956c2fc04f455508b', 'date_insert__993': datetime.datetime(2023, 12, 24, 1, 20, 54), 'date_update__993': datetime.datetime(2023, 12, 24, 1, 20, 54), 'fuser_id__993': 62514840, 'user_id__994': None, 'code__994': '961a67507f097835bd8a0644f59d76f3', 'date_insert__994': datetime.datetime(2023, 12, 24, 1, 21, 3), 'date_update__994': datetime.datetime(2023, 12, 24, 1, 21, 3), 'fuser_id__994': 62514841, 'user_id__995': None, 'code__995': '43006973f0c53fe4df4ec5a037c8534f', 'date_insert__995': datetime.datetime(2023, 12, 24, 1, 21, 3), 'date_update__995': datetime.datetime(2023, 12, 24, 1, 21, 3), 'fuser_id__995': 62514842, 'user_id__996': None, 'code__996': 'aedb112b6f223f2c3a928be2d9283c8f', 'date_insert__996': datetime.datetime(2023, 12, 24, 1, 21, 6), 'date_update__996': datetime.datetime(2023, 12, 24, 1, 21, 6), 'fuser_id__996': 62514843, 'user_id__997': None, 'code__997': '1e2dad878bf0aa2c1146a7f7f8bc4c37', 'date_insert__997': datetime.datetime(2023, 12, 24, 1, 21, 11), 'date_update__997': datetime.datetime(2023, 12, 24, 1, 21, 11), 'fuser_id__997': 62514844, 'user_id__998': None, 'code__998': '76bd48935133ef0aefd3d653608aaec3', 'date_insert__998': datetime.datetime(2023, 12, 24, 1, 21, 27), 'date_update__998': datetime.datetime(2023, 12, 24, 1, 21, 27), 'fuser_id__998': 62514845, 'user_id__999': None, 'code__999': '5644d0617e90f8f27300fda5bf0a50d5', 'date_insert__999': datetime.datetime(2023, 12, 24, 1, 21, 59), 'date_update__999': datetime.datetime(2023, 12, 24, 1, 21, 59), 'fuser_id__999': 62514846}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
Traceback (most recent call last):
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 2112, in _exec_insertmany_context
    dialect.do_execute(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "site_insert_fuser_new_fuser_id_key"
DETAIL:  Key (fuser_id)=(62513845) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "g:\py.projects\tb\data_collection\site_dat\load_data_site.py", line 95, in dataSiteToBd
    df.to_sql(tableName, engine_pg, schema='public', if_exists='append', index=False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\core\generic.py", line 3008, in to_sql
    return sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1958, in to_sql
    total_inserted = sql_engine.insert_records(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1507, in insert_records
    raise err
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1498, in insert_records
    return table.insert(chunksize=chunksize, method=method)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1059, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 951, in _execute_insert
    result = conn.execute(self.table.insert(), data)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\sql\elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1639, in _execute_clauseelement
    ret = self._execute_context(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1843, in _execute_context
    return self._exec_insertmany_context(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 2120, in _exec_insertmany_context
    self._handle_dbapi_exception(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 2343, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 2112, in _exec_insertmany_context
    dialect.do_execute(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "site_insert_fuser_new_fuser_id_key"
DETAIL:  Key (fuser_id)=(62513845) already exists.

[SQL: INSERT INTO public.site_insert_fuser_new (fuser_id, date_insert, date_update, user_id, code) VALUES (%(fuser_id__0)s, %(date_insert__0)s, %(date_update__0)s, %(user_id__0)s, %(code__0)s), (%(fuser_id__1)s, %(date_insert__1)s, %(date_update__1)s, %(us ... 97198 characters truncated ... s), (%(fuser_id__999)s, %(date_insert__999)s, %(date_update__999)s, %(user_id__999)s, %(code__999)s)]
[parameters: {'user_id__0': None, 'code__0': 'd81e7090d18155286b91689dcc1a1998', 'date_insert__0': datetime.datetime(2023, 12, 24, 0, 0, 3), 'date_update__0': datetime.datetime(2023, 12, 24, 0, 0, 3), 'fuser_id__0': 62513845, 'user_id__1': None, 'code__1': 'de426c0156877e94d5218a461aff2efe', 'date_insert__1': datetime.datetime(2023, 12, 24, 0, 0, 3), 'date_update__1': datetime.datetime(2023, 12, 24, 0, 0, 3), 'fuser_id__1': 62513846, 'user_id__2': None, 'code__2': '347473677c13e2a5a948d7580fb21245', 'date_insert__2': datetime.datetime(2023, 12, 24, 0, 0, 4), 'date_update__2': datetime.datetime(2023, 12, 24, 0, 0, 4), 'fuser_id__2': 62513847, 'user_id__3': None, 'code__3': '6dd35bd1438ad4ecfa54f491e3f2a06f', 'date_insert__3': datetime.datetime(2023, 12, 24, 0, 0, 21), 'date_update__3': datetime.datetime(2023, 12, 24, 0, 0, 21), 'fuser_id__3': 62513848, 'user_id__4': None, 'code__4': 'd30272576af30843e1645f3aed6cec56', 'date_insert__4': datetime.datetime(2023, 12, 24, 0, 0, 21), 'date_update__4': datetime.datetime(2023, 12, 24, 0, 0, 21), 'fuser_id__4': 62513849, 'user_id__5': None, 'code__5': '081e28e2d8c9ba3d80820f401b729fb8', 'date_insert__5': datetime.datetime(2023, 12, 24, 0, 0, 21), 'date_update__5': datetime.datetime(2023, 12, 24, 0, 0, 21), 'fuser_id__5': 62513850, 'user_id__6': None, 'code__6': '41ac659d356e3edfc6cccde3368a6113', 'date_insert__6': datetime.datetime(2023, 12, 24, 0, 0, 32), 'date_update__6': datetime.datetime(2023, 12, 25, 9, 6, 58), 'fuser_id__6': 62513851, 'user_id__7': None, 'code__7': '21a0ef33528ec46912b61101d81e6476', 'date_insert__7': datetime.datetime(2023, 12, 24, 0, 0, 57), 'date_update__7': datetime.datetime(2023, 12, 24, 0, 0, 57), 'fuser_id__7': 62513852, 'user_id__8': None, 'code__8': '36f7b02d82ca598592c68b0507a7f219', 'date_insert__8': datetime.datetime(2023, 12, 24, 0, 1, 11), 'date_update__8': datetime.datetime(2023, 12, 24, 0, 1, 11), 'fuser_id__8': 62513853, 'user_id__9': None, 'code__9': '0467a2e45b19268044fc85f5b51797ba', 'date_insert__9': datetime.datetime(2023, 12, 24, 0, 1, 11), 'date_update__9': datetime.datetime(2023, 12, 24, 0, 1, 11), 'fuser_id__9': 62513854 ... 4900 parameters truncated ... 'user_id__990': None, 'code__990': 'c061c96b6870ad4b74707108c4d8cefd', 'date_insert__990': datetime.datetime(2023, 12, 24, 1, 20, 18), 'date_update__990': datetime.datetime(2023, 12, 24, 1, 20, 18), 'fuser_id__990': 62514837, 'user_id__991': None, 'code__991': 'ee744405132c456c88e9c65fbf565ff2', 'date_insert__991': datetime.datetime(2023, 12, 24, 1, 20, 25), 'date_update__991': datetime.datetime(2023, 12, 24, 12, 26, 44), 'fuser_id__991': 62514838, 'user_id__992': None, 'code__992': '87d3072b24639b0e349925ae824080fa', 'date_insert__992': datetime.datetime(2023, 12, 24, 1, 20, 53), 'date_update__992': datetime.datetime(2023, 12, 24, 1, 20, 53), 'fuser_id__992': 62514839, 'user_id__993': None, 'code__993': '14d17beba1e3515956c2fc04f455508b', 'date_insert__993': datetime.datetime(2023, 12, 24, 1, 20, 54), 'date_update__993': datetime.datetime(2023, 12, 24, 1, 20, 54), 'fuser_id__993': 62514840, 'user_id__994': None, 'code__994': '961a67507f097835bd8a0644f59d76f3', 'date_insert__994': datetime.datetime(2023, 12, 24, 1, 21, 3), 'date_update__994': datetime.datetime(2023, 12, 24, 1, 21, 3), 'fuser_id__994': 62514841, 'user_id__995': None, 'code__995': '43006973f0c53fe4df4ec5a037c8534f', 'date_insert__995': datetime.datetime(2023, 12, 24, 1, 21, 3), 'date_update__995': datetime.datetime(2023, 12, 24, 1, 21, 3), 'fuser_id__995': 62514842, 'user_id__996': None, 'code__996': 'aedb112b6f223f2c3a928be2d9283c8f', 'date_insert__996': datetime.datetime(2023, 12, 24, 1, 21, 6), 'date_update__996': datetime.datetime(2023, 12, 24, 1, 21, 6), 'fuser_id__996': 62514843, 'user_id__997': None, 'code__997': '1e2dad878bf0aa2c1146a7f7f8bc4c37', 'date_insert__997': datetime.datetime(2023, 12, 24, 1, 21, 11), 'date_update__997': datetime.datetime(2023, 12, 24, 1, 21, 11), 'fuser_id__997': 62514844, 'user_id__998': None, 'code__998': '76bd48935133ef0aefd3d653608aaec3', 'date_insert__998': datetime.datetime(2023, 12, 24, 1, 21, 27), 'date_update__998': datetime.datetime(2023, 12, 24, 1, 21, 27), 'fuser_id__998': 62514845, 'user_id__999': None, 'code__999': '5644d0617e90f8f27300fda5bf0a50d5', 'date_insert__999': datetime.datetime(2023, 12, 24, 1, 21, 59), 'date_update__999': datetime.datetime(2023, 12, 24, 1, 21, 59), 'fuser_id__999': 62514846}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
root 2023-12-25 12:30:05,132 INFO siteUpdateFuser(). Podkluchenie k base site i otptavka zaprosa.
paramiko.transport 2023-12-25 12:30:05,158 INFO Connected (version 2.0, client OpenSSH_7.4)
paramiko.transport 2023-12-25 12:30:05,528 INFO Authentication (password) successful!
root 2023-12-25 12:30:06,573 INFO siteUpdateFuser(). Uspeshnoe poluchenie dannih.
root 2023-12-25 12:30:06,576 INFO site.dataSiteToBd(). Zapis dataframe v tablitsu site_update_fuser_new.
root 2023-12-25 12:30:07,152 INFO site.dataSiteToBd(). Dataframe uspeshno zapisan v tablitsu - site_update_fuser_new.
root 2023-12-25 12:30:07,153 INFO siteGuest(). Podkluchenie k base site i otptavka zaprosa.
paramiko.transport 2023-12-25 12:30:07,181 INFO Connected (version 2.0, client OpenSSH_7.4)
paramiko.transport 2023-12-25 12:30:07,508 INFO Authentication (password) successful!
root 2023-12-25 12:30:16,865 INFO siteGuest(). Uspeshnoe poluchenie dannih.
root 2023-12-25 12:30:16,881 INFO site.dataSiteToBd(). Zapis dataframe v tablitsu site_guest_new.
root 2023-12-25 12:30:17,192 ERROR site.dataSiteToBd(). Oshibka zapisi dannih v tab site_guest_new - (psycopg2.errors.StringDataRightTruncation) value too long for type character(1)

[SQL: INSERT INTO public.site_guest_new (guest_id, timestamp_x, favorites, c_events, sessions, hits, repair, first_session_id, first_date, first_url_from, first_url_to, first_url_to_404, first_site_id, first_adv_id, first_referer1, first_referer2, first_re ... 748965 characters truncated ... )s, %(last_site_id__907)s, %(last_country_id__907)s, %(last_city_id__907)s, %(last_city_info__907)s)]
[parameters: {'last_user_auth__0': 'N', 'c_events__0': 0, 'last_referer3__0': None, 'guest_id__0': 3085830, 'last_referer1__0': None, 'first_url_from__0': None, 'favorites__0': 'N', 'last_url_last_404__0': 'N', 'first_referer3__0': None, 'last_city_info__0': 'a:4:{s:2:"LC";s:27:"CCityLookup_geoip_extension";s:2:"LD";a:3:{s:3:"IPA";s:11:"17.241.75.6";s:3:"IPN";s:9:"301026054";s:3:"COC";s:2:"US";}s:2:"CC";s:2:"US";s:2:"CI";s:1:"1";}', 'last_url_last__0': 'https://usp-screw.top:443/futbolki/', 'last_adv_id__0': None, 'first_adv_id__0': 0, 'last_user_agent__0': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15 (Applebot/0.1; +http://www.apple.com/go/applebot)', 'timestamp_x__0': None, 'first_referer1__0': None, 'last_adv_back__0': 'N', 'last_language__0': None, 'last_site_id__0': 's1', 'first_referer2__0': None, 'first_date__0': datetime.datetime(2023, 12, 24, 0, 0, 3), 'first_url_to__0': 'https://usp-screw.top:443/futbolki/protiv_techeniya/', 'last_user_id__0': 0, 'last_ip__0': '17.241.75.6', 'first_site_id__0': 's1', 'last_city_id__0': 1, 'first_url_to_404__0': 'N', 'sessions__0': 1, 'last_cookie__0': None, 'hits__0': 2, 'last_referer2__0': None, 'last_session_id__0': 5548402, 'last_date__0': datetime.datetime(2023, 12, 24, 0, 0, 4), 'first_session_id__0': 5548402.0, 'last_country_id__0': 'US', 'repair__0': 'N', 'last_user_auth__1': 'N', 'c_events__1': 0, 'last_referer3__1': None, 'guest_id__1': 3085831, 'last_referer1__1': None, 'first_url_from__1': 'http://charutti.ru/platya_charutti/ofisnye_platya/schastlivaya_biznes/', 'favorites__1': 'N', 'last_url_last_404__1': 'N', 'first_referer3__1': None, 'last_city_info__1': 'a:4:{s:2:"LC";s:27:"CCityLookup_geoip_extension";s:2:"LD";a:3:{s:3:"IPA";s:13:"15.235.48.150";s:3:"IPN";s:9:"267071638";s:3:"COC";s:2:"US";}s:2:"CC";s:2:"US";s:2:"CI";s:1:"1";}', 'last_url_last__1': 'https://charutti.ru:443/platya_charutti/ofisnye_platya/schastlivaya_biznes/', 'last_adv_id__1': None, 'first_adv_id__1': 0, 'last_user_agent__1': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36' ... 32588 parameters truncated ... 'last_user_id__906': 0, 'last_ip__906': '66.249.64.102', 'first_site_id__906': 's1', 'last_city_id__906': 1, 'first_url_to_404__906': 'N', 'sessions__906': 1, 'last_cookie__906': None, 'hits__906': 1, 'last_referer2__906': None, 'last_session_id__906': 5549910, 'last_date__906': datetime.datetime(2023, 12, 24, 3, 16), 'first_session_id__906': 5549910.0, 'last_country_id__906': 'US', 'repair__906': 'N', 'last_user_auth__907': 'N', 'c_events__907': 0, 'last_referer3__907': None, 'guest_id__907': 3086737, 'last_referer1__907': None, 'first_url_from__907': 'https://charutti.ru/tuniki/', 'favorites__907': 'N', 'last_url_last_404__907': 'N', 'first_referer3__907': None, 'last_city_info__907': 'a:4:{s:2:"LC";s:27:"CCityLookup_geoip_extension";s:2:"LD";a:3:{s:3:"IPA";s:13:"66.249.64.101";s:3:"IPN";s:10:"1123631205";s:3:"COC";s:2:"US";}s:2:"CC";s:2:"US";s:2:"CI";s:1:"1";}', 'last_url_last__907': 'https://charutti.ru:443/', 'last_adv_id__907': None, 'first_adv_id__907': 0, 'last_user_agent__907': 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Googlebot/2.1; +http://www.google.com/bot.html) Chrome/120.0.6099.71 Safari/537.36', 'timestamp_x__907': None, 'first_referer1__907': None, 'last_adv_back__907': 'N', 'last_language__907': 'en-US', 'last_site_id__907': 's1', 'first_referer2__907': None, 'first_date__907': datetime.datetime(2023, 12, 24, 3, 16, 3), 'first_url_to__907': 'https://charutti.ru:443/tuniki/', 'last_user_id__907': 0, 'last_ip__907': '66.249.64.109', 'first_site_id__907': 's1', 'last_city_id__907': 1, 'first_url_to_404__907': 'N', 'sessions__907': 1, 'last_cookie__907': '[_ym_uid] = 1703361600318392746\n[_ym_d] = 1703361600\n[tmr_lvid] = d3eb3f55de6ca40649d896a724265f9d\n[tmr_lvidTS] = 1703361600051\n[PHPSESSID] = xcclG53WlAqLQPG7xsIHnM6SpyjwTIgL\n', 'hits__907': 3, 'last_referer2__907': None, 'last_session_id__907': 5549911, 'last_date__907': datetime.datetime(2023, 12, 24, 3, 37, 37), 'first_session_id__907': 5549911.0, 'last_country_id__907': 'US', 'repair__907': 'N'}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
Traceback (most recent call last):
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 2112, in _exec_insertmany_context
    dialect.do_execute(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.StringDataRightTruncation: value too long for type character(1)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "g:\py.projects\tb\data_collection\site_dat\load_data_site.py", line 95, in dataSiteToBd
    df.to_sql(tableName, engine_pg, schema='public', if_exists='append', index=False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\core\generic.py", line 3008, in to_sql
    return sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1958, in to_sql
    total_inserted = sql_engine.insert_records(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1507, in insert_records
    raise err
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1498, in insert_records
    return table.insert(chunksize=chunksize, method=method)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1059, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 951, in _execute_insert
    result = conn.execute(self.table.insert(), data)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\sql\elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1639, in _execute_clauseelement
    ret = self._execute_context(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1843, in _execute_context
    return self._exec_insertmany_context(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 2120, in _exec_insertmany_context
    self._handle_dbapi_exception(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 2343, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 2112, in _exec_insertmany_context
    dialect.do_execute(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\sqlalchemy\engine\default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError: (psycopg2.errors.StringDataRightTruncation) value too long for type character(1)

[SQL: INSERT INTO public.site_guest_new (guest_id, timestamp_x, favorites, c_events, sessions, hits, repair, first_session_id, first_date, first_url_from, first_url_to, first_url_to_404, first_site_id, first_adv_id, first_referer1, first_referer2, first_re ... 748965 characters truncated ... )s, %(last_site_id__907)s, %(last_country_id__907)s, %(last_city_id__907)s, %(last_city_info__907)s)]
[parameters: {'last_user_auth__0': 'N', 'c_events__0': 0, 'last_referer3__0': None, 'guest_id__0': 3085830, 'last_referer1__0': None, 'first_url_from__0': None, 'favorites__0': 'N', 'last_url_last_404__0': 'N', 'first_referer3__0': None, 'last_city_info__0': 'a:4:{s:2:"LC";s:27:"CCityLookup_geoip_extension";s:2:"LD";a:3:{s:3:"IPA";s:11:"17.241.75.6";s:3:"IPN";s:9:"301026054";s:3:"COC";s:2:"US";}s:2:"CC";s:2:"US";s:2:"CI";s:1:"1";}', 'last_url_last__0': 'https://usp-screw.top:443/futbolki/', 'last_adv_id__0': None, 'first_adv_id__0': 0, 'last_user_agent__0': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15 (Applebot/0.1; +http://www.apple.com/go/applebot)', 'timestamp_x__0': None, 'first_referer1__0': None, 'last_adv_back__0': 'N', 'last_language__0': None, 'last_site_id__0': 's1', 'first_referer2__0': None, 'first_date__0': datetime.datetime(2023, 12, 24, 0, 0, 3), 'first_url_to__0': 'https://usp-screw.top:443/futbolki/protiv_techeniya/', 'last_user_id__0': 0, 'last_ip__0': '17.241.75.6', 'first_site_id__0': 's1', 'last_city_id__0': 1, 'first_url_to_404__0': 'N', 'sessions__0': 1, 'last_cookie__0': None, 'hits__0': 2, 'last_referer2__0': None, 'last_session_id__0': 5548402, 'last_date__0': datetime.datetime(2023, 12, 24, 0, 0, 4), 'first_session_id__0': 5548402.0, 'last_country_id__0': 'US', 'repair__0': 'N', 'last_user_auth__1': 'N', 'c_events__1': 0, 'last_referer3__1': None, 'guest_id__1': 3085831, 'last_referer1__1': None, 'first_url_from__1': 'http://charutti.ru/platya_charutti/ofisnye_platya/schastlivaya_biznes/', 'favorites__1': 'N', 'last_url_last_404__1': 'N', 'first_referer3__1': None, 'last_city_info__1': 'a:4:{s:2:"LC";s:27:"CCityLookup_geoip_extension";s:2:"LD";a:3:{s:3:"IPA";s:13:"15.235.48.150";s:3:"IPN";s:9:"267071638";s:3:"COC";s:2:"US";}s:2:"CC";s:2:"US";s:2:"CI";s:1:"1";}', 'last_url_last__1': 'https://charutti.ru:443/platya_charutti/ofisnye_platya/schastlivaya_biznes/', 'last_adv_id__1': None, 'first_adv_id__1': 0, 'last_user_agent__1': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36' ... 32588 parameters truncated ... 'last_user_id__906': 0, 'last_ip__906': '66.249.64.102', 'first_site_id__906': 's1', 'last_city_id__906': 1, 'first_url_to_404__906': 'N', 'sessions__906': 1, 'last_cookie__906': None, 'hits__906': 1, 'last_referer2__906': None, 'last_session_id__906': 5549910, 'last_date__906': datetime.datetime(2023, 12, 24, 3, 16), 'first_session_id__906': 5549910.0, 'last_country_id__906': 'US', 'repair__906': 'N', 'last_user_auth__907': 'N', 'c_events__907': 0, 'last_referer3__907': None, 'guest_id__907': 3086737, 'last_referer1__907': None, 'first_url_from__907': 'https://charutti.ru/tuniki/', 'favorites__907': 'N', 'last_url_last_404__907': 'N', 'first_referer3__907': None, 'last_city_info__907': 'a:4:{s:2:"LC";s:27:"CCityLookup_geoip_extension";s:2:"LD";a:3:{s:3:"IPA";s:13:"66.249.64.101";s:3:"IPN";s:10:"1123631205";s:3:"COC";s:2:"US";}s:2:"CC";s:2:"US";s:2:"CI";s:1:"1";}', 'last_url_last__907': 'https://charutti.ru:443/', 'last_adv_id__907': None, 'first_adv_id__907': 0, 'last_user_agent__907': 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Googlebot/2.1; +http://www.google.com/bot.html) Chrome/120.0.6099.71 Safari/537.36', 'timestamp_x__907': None, 'first_referer1__907': None, 'last_adv_back__907': 'N', 'last_language__907': 'en-US', 'last_site_id__907': 's1', 'first_referer2__907': None, 'first_date__907': datetime.datetime(2023, 12, 24, 3, 16, 3), 'first_url_to__907': 'https://charutti.ru:443/tuniki/', 'last_user_id__907': 0, 'last_ip__907': '66.249.64.109', 'first_site_id__907': 's1', 'last_city_id__907': 1, 'first_url_to_404__907': 'N', 'sessions__907': 1, 'last_cookie__907': '[_ym_uid] = 1703361600318392746\n[_ym_d] = 1703361600\n[tmr_lvid] = d3eb3f55de6ca40649d896a724265f9d\n[tmr_lvidTS] = 1703361600051\n[PHPSESSID] = xcclG53WlAqLQPG7xsIHnM6SpyjwTIgL\n', 'hits__907': 3, 'last_referer2__907': None, 'last_session_id__907': 5549911, 'last_date__907': datetime.datetime(2023, 12, 24, 3, 37, 37), 'first_session_id__907': 5549911.0, 'last_country_id__907': 'US', 'repair__907': 'N'}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
root 2023-12-25 12:30:17,196 INFO siteSession(). Podkluchenie k base site i otptavka zaprosa.
paramiko.transport 2023-12-25 12:30:17,218 INFO Connected (version 2.0, client OpenSSH_7.4)
paramiko.transport 2023-12-25 12:30:17,572 INFO Authentication (password) successful!
root 2023-12-25 12:30:32,443 INFO siteSession(). Uspeshnoe poluchenie dannih.
root 2023-12-25 12:30:32,469 INFO site.dataSiteToBd(). Zapis dataframe v tablitsu site_session_new.
root 2023-12-25 12:30:34,218 INFO site.dataSiteToBd(). Dataframe uspeshno zapisan v tablitsu - site_session_new.
root 2023-12-25 12:30:34,219 INFO siteOrderPropsValue(). Podkluchenie k base site i otptavka zaprosa.
paramiko.transport 2023-12-25 12:30:34,242 INFO Connected (version 2.0, client OpenSSH_7.4)
paramiko.transport 2023-12-25 12:30:34,645 INFO Authentication (password) successful!
root 2023-12-25 12:30:38,692 INFO siteOrderPropsValue(). Uspeshnoe poluchenie dannih.
root 2023-12-25 12:30:38,697 INFO site.dataSiteToBd(). Zapis dataframe v tablitsu site_order_props_value_new.
root 2023-12-25 12:30:38,780 INFO site.dataSiteToBd(). Dataframe uspeshno zapisan v tablitsu - site_order_props_value_new.
root 2023-12-25 12:30:38,780 INFO siteTransact(). Podkluchenie k base site i otptavka zaprosa.
paramiko.transport 2023-12-25 12:30:38,809 INFO Connected (version 2.0, client OpenSSH_7.4)
paramiko.transport 2023-12-25 12:30:39,160 INFO Authentication (password) successful!
root 2023-12-25 12:30:39,841 INFO siteTransact(). Uspeshnoe poluchenie dannih.
root 2023-12-25 12:30:39,843 INFO site.dataSiteToBd(). Zapis dataframe v tablitsu site_user_transact.
root 2023-12-25 12:30:39,949 INFO site.dataSiteToBd(). Dataframe uspeshno zapisan v tablitsu - site_user_transact.
