root 2023-11-29 10:34:52,950 INFO Step_1_hits. Creating a log.
root 2023-11-29 10:34:53,458 INFO Code status 200
NoneType: None
root 2023-11-29 10:34:53,458 INFO Step_1_hits. Successful log request.
root 2023-11-29 10:34:53,458 INFO Step_1_hits. Request number 32806564.
root 2023-11-29 10:34:53,458 INFO Step_1_hits. Request status created.
root 2023-11-29 10:34:53,458 INFO Step_2_hits. Log processing status.
root 2023-11-29 10:34:53,668 INFO Step_2_hits. Loading data. Code 200.
root 2023-11-29 10:35:09,310 INFO Step_2_hits. Number of parts - 1.
root 2023-11-29 10:35:09,310 INFO Step_2_hits. Request status processed.
root 2023-11-29 10:35:09,325 INFO Step_3_hits. Loading the log.
root 2023-11-29 10:35:09,708 INFO Step_3_hits. Loading a log from one part.
root 2023-11-29 10:35:09,708 INFO Step_4_hits. Deleting a log.
root 2023-11-29 10:35:09,926 INFO Step_4_hits. Successful log deletion # 32806564.
root 2023-11-29 10:35:09,926 INFO Step_4_hits. Deleting variables.
root 2023-11-29 10:35:09,927 INFO Start clearing data HITS.
root 2023-11-29 10:35:09,928 INFO Reading data HITS and writing to a dataframe.
root 2023-11-29 10:35:10,011 INFO Renaming columns HITS.
root 2023-11-29 10:35:10,039 INFO Clearing data HITS.
root 2023-11-29 10:35:10,051 INFO Start zagruzka v bazu logs api HITS.
root 2023-11-29 10:35:10,161 INFO Start zagruzka dannih - ym_hits_stranitsi_new.
root 2023-11-29 10:35:10,248 ERROR Error: oshibka zagruzki v tablitsu - ym_hits_stranitsi_new - Unsigned 64 bit integer datatype is not supported
Traceback (most recent call last):
  File "g:\py.projects\tb\data_collection\ya_metric\zagruzka_v_db.py", line 34, in ya_hits_to_bd
    col.to_sql('ym_hits_stranitsi_new', engine, schema='public', if_exists='append', index=False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\core\generic.py", line 3008, in to_sql
    return sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1948, in to_sql
    table = self.prep_table(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1842, in prep_table
    table = SQLTable(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 899, in __init__
    self.table = self._create_table_setup()
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1205, in _create_table_setup
    column_names_and_types = self._get_column_names_and_types(self._sqlalchemy_type)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1190, in _get_column_names_and_types
    column_names_and_types += [
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1191, in <listcomp>
    (str(self.frame.columns[i]), dtype_mapper(self.frame.iloc[:, i]), False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1339, in _sqlalchemy_type
    raise ValueError("Unsigned 64 bit integer datatype is not supported")
ValueError: Unsigned 64 bit integer datatype is not supported
root 2023-11-29 10:35:10,364 INFO Start zagruzka dannih - ym_hits_obshee_new.
root 2023-11-29 10:35:10,365 ERROR Error: oshibka zagruzki v tablitsu - ym_hits_obshee_new - Unsigned 64 bit integer datatype is not supported
Traceback (most recent call last):
  File "g:\py.projects\tb\data_collection\ya_metric\zagruzka_v_db.py", line 47, in ya_hits_to_bd
    col.to_sql('ym_hits_obshee_new', engine, schema='public', if_exists='append', index=False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\core\generic.py", line 3008, in to_sql
    return sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1948, in to_sql
    table = self.prep_table(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1842, in prep_table
    table = SQLTable(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 899, in __init__
    self.table = self._create_table_setup()
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1205, in _create_table_setup
    column_names_and_types = self._get_column_names_and_types(self._sqlalchemy_type)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1190, in _get_column_names_and_types
    column_names_and_types += [
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1191, in <listcomp>
    (str(self.frame.columns[i]), dtype_mapper(self.frame.iloc[:, i]), False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1339, in _sqlalchemy_type
    raise ValueError("Unsigned 64 bit integer datatype is not supported")
ValueError: Unsigned 64 bit integer datatype is not supported
root 2023-11-29 10:35:10,366 INFO Start zagruzka dannih - ym_hits_deystviya_new.
root 2023-11-29 10:35:10,368 ERROR Error: oshibka zagruzki v tablitsu - ym_hits_deystviya_new - Unsigned 64 bit integer datatype is not supported
Traceback (most recent call last):
  File "g:\py.projects\tb\data_collection\ya_metric\zagruzka_v_db.py", line 60, in ya_hits_to_bd
    col.to_sql('ym_hits_deystviya_new', engine, schema='public', if_exists='append', index=False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\core\generic.py", line 3008, in to_sql
    return sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1948, in to_sql
    table = self.prep_table(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1842, in prep_table
    table = SQLTable(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 899, in __init__
    self.table = self._create_table_setup()
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1205, in _create_table_setup
    column_names_and_types = self._get_column_names_and_types(self._sqlalchemy_type)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1190, in _get_column_names_and_types
    column_names_and_types += [
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1191, in <listcomp>
    (str(self.frame.columns[i]), dtype_mapper(self.frame.iloc[:, i]), False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1339, in _sqlalchemy_type
    raise ValueError("Unsigned 64 bit integer datatype is not supported")
ValueError: Unsigned 64 bit integer datatype is not supported
root 2023-11-29 10:35:10,368 INFO Start zagruzka dannih - ym_hits_ad_new.
root 2023-11-29 10:35:10,370 ERROR Error: oshibka zagruzki v tablitsu - ym_hits_ad_new - Unsigned 64 bit integer datatype is not supported
Traceback (most recent call last):
  File "g:\py.projects\tb\data_collection\ya_metric\zagruzka_v_db.py", line 73, in ya_hits_to_bd
    col.to_sql('ym_hits_ad_new', engine, schema='public', if_exists='append', index=False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\core\generic.py", line 3008, in to_sql
    return sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1948, in to_sql
    table = self.prep_table(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1842, in prep_table
    table = SQLTable(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 899, in __init__
    self.table = self._create_table_setup()
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1205, in _create_table_setup
    column_names_and_types = self._get_column_names_and_types(self._sqlalchemy_type)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1190, in _get_column_names_and_types
    column_names_and_types += [
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1191, in <listcomp>
    (str(self.frame.columns[i]), dtype_mapper(self.frame.iloc[:, i]), False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1339, in _sqlalchemy_type
    raise ValueError("Unsigned 64 bit integer datatype is not supported")
ValueError: Unsigned 64 bit integer datatype is not supported
root 2023-11-29 10:37:05,605 INFO Step_1_hits. Creating a log.
root 2023-11-29 10:37:05,882 INFO Code status 200
NoneType: None
root 2023-11-29 10:37:05,882 INFO Step_1_hits. Successful log request.
root 2023-11-29 10:37:05,882 INFO Step_1_hits. Request number 32806640.
root 2023-11-29 10:37:05,882 INFO Step_1_hits. Request status created.
root 2023-11-29 10:37:05,882 INFO Step_2_hits. Log processing status.
root 2023-11-29 10:37:06,083 INFO Step_2_hits. Loading data. Code 200.
root 2023-11-29 10:39:05,976 INFO Step_2_hits. Number of parts - 1.
root 2023-11-29 10:39:05,976 INFO Step_2_hits. Request status processed.
root 2023-11-29 10:39:05,976 INFO Step_3_hits. Loading the log.
root 2023-11-29 10:39:06,449 INFO Step_3_hits. Loading a log from one part.
root 2023-11-29 10:39:06,449 INFO Step_4_hits. Deleting a log.
root 2023-11-29 10:39:06,640 INFO Step_4_hits. Successful log deletion # 32806640.
root 2023-11-29 10:39:06,640 INFO Step_4_hits. Deleting variables.
root 2023-11-29 10:39:06,641 INFO Start clearing data HITS.
root 2023-11-29 10:39:06,641 INFO Reading data HITS and writing to a dataframe.
root 2023-11-29 10:39:06,672 INFO Renaming columns HITS.
root 2023-11-29 10:39:06,673 INFO Clearing data HITS.
root 2023-11-29 10:39:06,683 INFO Start zagruzka v bazu logs api HITS.
root 2023-11-29 10:39:06,762 INFO Start zagruzka dannih - ym_hits_stranitsi_new.
root 2023-11-29 10:39:06,764 ERROR Error: oshibka zagruzki v tablitsu - ym_hits_stranitsi_new - Unsigned 64 bit integer datatype is not supported
Traceback (most recent call last):
  File "g:\py.projects\tb\data_collection\ya_metric\zagruzka_v_db.py", line 34, in ya_hits_to_bd
    col.to_sql('ym_hits_stranitsi_new', engine, schema='public', if_exists='append', index=False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\core\generic.py", line 3008, in to_sql
    return sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1948, in to_sql
    table = self.prep_table(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1842, in prep_table
    table = SQLTable(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 899, in __init__
    self.table = self._create_table_setup()
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1205, in _create_table_setup
    column_names_and_types = self._get_column_names_and_types(self._sqlalchemy_type)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1190, in _get_column_names_and_types
    column_names_and_types += [
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1191, in <listcomp>
    (str(self.frame.columns[i]), dtype_mapper(self.frame.iloc[:, i]), False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1339, in _sqlalchemy_type
    raise ValueError("Unsigned 64 bit integer datatype is not supported")
ValueError: Unsigned 64 bit integer datatype is not supported
root 2023-11-29 10:39:06,764 INFO Start zagruzka dannih - ym_hits_obshee_new.
root 2023-11-29 10:39:06,766 ERROR Error: oshibka zagruzki v tablitsu - ym_hits_obshee_new - Unsigned 64 bit integer datatype is not supported
Traceback (most recent call last):
  File "g:\py.projects\tb\data_collection\ya_metric\zagruzka_v_db.py", line 47, in ya_hits_to_bd
    col.to_sql('ym_hits_obshee_new', engine, schema='public', if_exists='append', index=False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\core\generic.py", line 3008, in to_sql
    return sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1948, in to_sql
    table = self.prep_table(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1842, in prep_table
    table = SQLTable(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 899, in __init__
    self.table = self._create_table_setup()
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1205, in _create_table_setup
    column_names_and_types = self._get_column_names_and_types(self._sqlalchemy_type)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1190, in _get_column_names_and_types
    column_names_and_types += [
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1191, in <listcomp>
    (str(self.frame.columns[i]), dtype_mapper(self.frame.iloc[:, i]), False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1339, in _sqlalchemy_type
    raise ValueError("Unsigned 64 bit integer datatype is not supported")
ValueError: Unsigned 64 bit integer datatype is not supported
root 2023-11-29 10:39:06,766 INFO Start zagruzka dannih - ym_hits_deystviya_new.
root 2023-11-29 10:39:06,767 ERROR Error: oshibka zagruzki v tablitsu - ym_hits_deystviya_new - Unsigned 64 bit integer datatype is not supported
Traceback (most recent call last):
  File "g:\py.projects\tb\data_collection\ya_metric\zagruzka_v_db.py", line 60, in ya_hits_to_bd
    col.to_sql('ym_hits_deystviya_new', engine, schema='public', if_exists='append', index=False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\core\generic.py", line 3008, in to_sql
    return sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1948, in to_sql
    table = self.prep_table(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1842, in prep_table
    table = SQLTable(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 899, in __init__
    self.table = self._create_table_setup()
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1205, in _create_table_setup
    column_names_and_types = self._get_column_names_and_types(self._sqlalchemy_type)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1190, in _get_column_names_and_types
    column_names_and_types += [
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1191, in <listcomp>
    (str(self.frame.columns[i]), dtype_mapper(self.frame.iloc[:, i]), False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1339, in _sqlalchemy_type
    raise ValueError("Unsigned 64 bit integer datatype is not supported")
ValueError: Unsigned 64 bit integer datatype is not supported
root 2023-11-29 10:39:06,768 INFO Start zagruzka dannih - ym_hits_ad_new.
root 2023-11-29 10:39:06,771 ERROR Error: oshibka zagruzki v tablitsu - ym_hits_ad_new - Unsigned 64 bit integer datatype is not supported
Traceback (most recent call last):
  File "g:\py.projects\tb\data_collection\ya_metric\zagruzka_v_db.py", line 73, in ya_hits_to_bd
    col.to_sql('ym_hits_ad_new', engine, schema='public', if_exists='append', index=False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\core\generic.py", line 3008, in to_sql
    return sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1948, in to_sql
    table = self.prep_table(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1842, in prep_table
    table = SQLTable(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 899, in __init__
    self.table = self._create_table_setup()
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1205, in _create_table_setup
    column_names_and_types = self._get_column_names_and_types(self._sqlalchemy_type)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1190, in _get_column_names_and_types
    column_names_and_types += [
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1191, in <listcomp>
    (str(self.frame.columns[i]), dtype_mapper(self.frame.iloc[:, i]), False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1339, in _sqlalchemy_type
    raise ValueError("Unsigned 64 bit integer datatype is not supported")
ValueError: Unsigned 64 bit integer datatype is not supported
root 2023-11-29 10:39:18,392 INFO Step_1_visit. Creating a log.
root 2023-11-29 10:39:18,641 INFO Code status 200
NoneType: None
root 2023-11-29 10:39:18,641 INFO Step_1_visit. Successful log request.
root 2023-11-29 10:39:18,641 INFO Step_1_visit. Request number 32806681.
root 2023-11-29 10:39:18,641 INFO Step_1_visit. Request status created.
root 2023-11-29 10:39:18,642 INFO Step_2_visit. Log processing status.
root 2023-11-29 10:39:18,843 INFO Step_2_visit. Loading data. Code 200.
root 2023-11-29 10:41:08,442 INFO Step_2_visit. Number of parts - 0.
root 2023-11-29 10:41:08,442 INFO Step_2_visit. Request status processed.
root 2023-11-29 10:41:08,442 INFO Step_3_visit. Loading the log.
root 2023-11-29 10:41:08,856 INFO Step_3_visit. Loading a log from one part.
root 2023-11-29 10:41:08,856 INFO Step_3_visit. Loading 0 parts of the log.
root 2023-11-29 10:41:08,856 INFO Step_4_visit. Deleting a log.
root 2023-11-29 10:41:09,031 INFO Step_4_visit. Successful log deletion # 32806681.
root 2023-11-29 10:41:09,032 INFO Step_4_visit. Deleting variables.
root 2023-11-29 10:41:09,033 INFO Start clearing data VISITS.
root 2023-11-29 10:41:09,033 INFO Reading data VISITS and writing to a dataframe.
root 2023-11-29 10:41:09,045 INFO Renaming columns VISITS.
root 2023-11-29 10:41:09,048 INFO Clearing data VISITS.
root 2023-11-29 10:41:09,095 INFO Start zagruzka v bazu logs api VISITS.
root 2023-11-29 10:41:09,153 INFO Start zagruzka dannih - ym_visits_obshee_new.
root 2023-11-29 10:41:09,155 ERROR Error: oshibka zagruzki v tablitsu - ym_visits_obshee_new - Unsigned 64 bit integer datatype is not supported
Traceback (most recent call last):
  File "g:\py.projects\tb\data_collection\ya_metric\zagruzka_v_db.py", line 99, in ya_visits_to_bd
    col.to_sql('ym_visits_obshee_new', engine, schema='public', if_exists='append', index=False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\core\generic.py", line 3008, in to_sql
    return sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1948, in to_sql
    table = self.prep_table(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1842, in prep_table
    table = SQLTable(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 899, in __init__
    self.table = self._create_table_setup()
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1205, in _create_table_setup
    column_names_and_types = self._get_column_names_and_types(self._sqlalchemy_type)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1190, in _get_column_names_and_types
    column_names_and_types += [
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1191, in <listcomp>
    (str(self.frame.columns[i]), dtype_mapper(self.frame.iloc[:, i]), False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1339, in _sqlalchemy_type
    raise ValueError("Unsigned 64 bit integer datatype is not supported")
ValueError: Unsigned 64 bit integer datatype is not supported
root 2023-11-29 10:41:09,155 INFO Start zagruzka dannih - # ym_visits_detali_new.
root 2023-11-29 10:41:09,157 ERROR Error: oshibka zagruzki v tablitsu - ym_visits_detali_new - Unsigned 64 bit integer datatype is not supported
Traceback (most recent call last):
  File "g:\py.projects\tb\data_collection\ya_metric\zagruzka_v_db.py", line 113, in ya_visits_to_bd
    col.to_sql('ym_visits_detali_new', engine, schema='public', if_exists='append', index=False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\core\generic.py", line 3008, in to_sql
    return sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1948, in to_sql
    table = self.prep_table(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1842, in prep_table
    table = SQLTable(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 899, in __init__
    self.table = self._create_table_setup()
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1205, in _create_table_setup
    column_names_and_types = self._get_column_names_and_types(self._sqlalchemy_type)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1190, in _get_column_names_and_types
    column_names_and_types += [
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1191, in <listcomp>
    (str(self.frame.columns[i]), dtype_mapper(self.frame.iloc[:, i]), False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1339, in _sqlalchemy_type
    raise ValueError("Unsigned 64 bit integer datatype is not supported")
ValueError: Unsigned 64 bit integer datatype is not supported
root 2023-11-29 10:41:28,481 INFO Otpravka soobsheniya v telegram.
root 2023-11-29 10:41:28,919 INFO Soobshenie v telegram otpravleno.
root 2023-11-29 10:57:56,409 INFO Step_1_hits. Creating a log.
root 2023-11-29 10:57:56,898 INFO Code status 200
NoneType: None
root 2023-11-29 10:57:56,898 INFO Step_1_hits. Successful log request.
root 2023-11-29 10:57:56,899 INFO Step_1_hits. Request number 32806852.
root 2023-11-29 10:57:56,899 INFO Step_1_hits. Request status created.
root 2023-11-29 10:57:56,899 INFO Step_2_hits. Log processing status.
root 2023-11-29 10:57:57,107 INFO Step_2_hits. Loading data. Code 200.
root 2023-11-29 10:58:07,596 INFO Step_2_hits. Number of parts - 1.
root 2023-11-29 10:58:07,596 INFO Step_2_hits. Request status processed.
root 2023-11-29 10:58:07,596 INFO Step_3_hits. Loading the log.
root 2023-11-29 10:58:08,030 INFO Step_3_hits. Loading a log from one part.
root 2023-11-29 10:58:08,030 INFO Step_4_hits. Deleting a log.
root 2023-11-29 10:58:08,260 INFO Step_4_hits. Successful log deletion # 32806852.
root 2023-11-29 10:58:08,260 INFO Step_4_hits. Deleting variables.
root 2023-11-29 10:58:08,262 INFO Start clearing data HITS.
root 2023-11-29 10:58:08,262 INFO Reading data HITS and writing to a dataframe.
root 2023-11-29 10:58:08,305 INFO Renaming columns HITS.
root 2023-11-29 10:58:08,307 INFO Clearing data HITS.
root 2023-11-29 10:58:08,319 INFO Start zagruzka v bazu logs api HITS.
root 2023-11-29 10:58:08,378 INFO Start zagruzka dannih - ym_hits_stranitsi_new.
root 2023-11-29 10:58:08,380 ERROR Error: oshibka zagruzki v tablitsu - ym_hits_stranitsi_new - Unsigned 64 bit integer datatype is not supported
Traceback (most recent call last):
  File "g:\py.projects\tb\data_collection\ya_metric\zagruzka_v_db.py", line 34, in ya_hits_to_bd
    col.to_sql('ym_hits_stranitsi_new', engine, schema='public', if_exists='append', index=False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\core\generic.py", line 3008, in to_sql
    return sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1948, in to_sql
    table = self.prep_table(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1842, in prep_table
    table = SQLTable(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 899, in __init__
    self.table = self._create_table_setup()
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1205, in _create_table_setup
    column_names_and_types = self._get_column_names_and_types(self._sqlalchemy_type)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1190, in _get_column_names_and_types
    column_names_and_types += [
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1191, in <listcomp>
    (str(self.frame.columns[i]), dtype_mapper(self.frame.iloc[:, i]), False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1339, in _sqlalchemy_type
    raise ValueError("Unsigned 64 bit integer datatype is not supported")
ValueError: Unsigned 64 bit integer datatype is not supported
root 2023-11-29 10:58:08,381 INFO Start zagruzka dannih - ym_hits_obshee_new.
root 2023-11-29 10:58:08,382 ERROR Error: oshibka zagruzki v tablitsu - ym_hits_obshee_new - Unsigned 64 bit integer datatype is not supported
Traceback (most recent call last):
  File "g:\py.projects\tb\data_collection\ya_metric\zagruzka_v_db.py", line 47, in ya_hits_to_bd
    col.to_sql('ym_hits_obshee_new', engine, schema='public', if_exists='append', index=False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\core\generic.py", line 3008, in to_sql
    return sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1948, in to_sql
    table = self.prep_table(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1842, in prep_table
    table = SQLTable(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 899, in __init__
    self.table = self._create_table_setup()
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1205, in _create_table_setup
    column_names_and_types = self._get_column_names_and_types(self._sqlalchemy_type)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1190, in _get_column_names_and_types
    column_names_and_types += [
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1191, in <listcomp>
    (str(self.frame.columns[i]), dtype_mapper(self.frame.iloc[:, i]), False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1339, in _sqlalchemy_type
    raise ValueError("Unsigned 64 bit integer datatype is not supported")
ValueError: Unsigned 64 bit integer datatype is not supported
root 2023-11-29 10:58:08,383 INFO Start zagruzka dannih - ym_hits_deystviya_new.
root 2023-11-29 10:58:08,384 ERROR Error: oshibka zagruzki v tablitsu - ym_hits_deystviya_new - Unsigned 64 bit integer datatype is not supported
Traceback (most recent call last):
  File "g:\py.projects\tb\data_collection\ya_metric\zagruzka_v_db.py", line 60, in ya_hits_to_bd
    col.to_sql('ym_hits_deystviya_new', engine, schema='public', if_exists='append', index=False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\core\generic.py", line 3008, in to_sql
    return sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1948, in to_sql
    table = self.prep_table(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1842, in prep_table
    table = SQLTable(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 899, in __init__
    self.table = self._create_table_setup()
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1205, in _create_table_setup
    column_names_and_types = self._get_column_names_and_types(self._sqlalchemy_type)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1190, in _get_column_names_and_types
    column_names_and_types += [
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1191, in <listcomp>
    (str(self.frame.columns[i]), dtype_mapper(self.frame.iloc[:, i]), False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1339, in _sqlalchemy_type
    raise ValueError("Unsigned 64 bit integer datatype is not supported")
ValueError: Unsigned 64 bit integer datatype is not supported
root 2023-11-29 10:58:08,384 INFO Start zagruzka dannih - ym_hits_ad_new.
root 2023-11-29 10:58:08,386 ERROR Error: oshibka zagruzki v tablitsu - ym_hits_ad_new - Unsigned 64 bit integer datatype is not supported
Traceback (most recent call last):
  File "g:\py.projects\tb\data_collection\ya_metric\zagruzka_v_db.py", line 73, in ya_hits_to_bd
    col.to_sql('ym_hits_ad_new', engine, schema='public', if_exists='append', index=False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\core\generic.py", line 3008, in to_sql
    return sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1948, in to_sql
    table = self.prep_table(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1842, in prep_table
    table = SQLTable(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 899, in __init__
    self.table = self._create_table_setup()
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1205, in _create_table_setup
    column_names_and_types = self._get_column_names_and_types(self._sqlalchemy_type)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1190, in _get_column_names_and_types
    column_names_and_types += [
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1191, in <listcomp>
    (str(self.frame.columns[i]), dtype_mapper(self.frame.iloc[:, i]), False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1339, in _sqlalchemy_type
    raise ValueError("Unsigned 64 bit integer datatype is not supported")
ValueError: Unsigned 64 bit integer datatype is not supported
root 2023-11-29 11:00:17,031 INFO Step_1_hits. Creating a log.
root 2023-11-29 11:00:17,292 INFO Code status 200
NoneType: None
root 2023-11-29 11:00:17,292 INFO Step_1_hits. Successful log request.
root 2023-11-29 11:00:17,292 INFO Step_1_hits. Request number 32806922.
root 2023-11-29 11:00:17,292 INFO Step_1_hits. Request status created.
root 2023-11-29 11:00:17,292 INFO Step_2_hits. Log processing status.
root 2023-11-29 11:00:17,493 INFO Step_2_hits. Loading data. Code 200.
root 2023-11-29 11:01:30,470 INFO Step_2_hits. Number of parts - 1.
root 2023-11-29 11:01:30,470 INFO Step_2_hits. Request status processed.
root 2023-11-29 11:01:30,470 INFO Step_3_hits. Loading the log.
root 2023-11-29 11:01:30,885 INFO Step_3_hits. Loading a log from one part.
root 2023-11-29 11:01:30,885 INFO Step_4_hits. Deleting a log.
root 2023-11-29 11:01:31,093 INFO Step_4_hits. Successful log deletion # 32806922.
root 2023-11-29 11:01:31,093 INFO Step_4_hits. Deleting variables.
root 2023-11-29 11:01:31,094 INFO Start clearing data HITS.
root 2023-11-29 11:01:31,094 INFO Reading data HITS and writing to a dataframe.
root 2023-11-29 11:01:31,112 INFO Renaming columns HITS.
root 2023-11-29 11:01:31,114 INFO Clearing data HITS.
root 2023-11-29 11:01:31,120 INFO Start zagruzka v bazu logs api HITS.
root 2023-11-29 11:01:31,222 INFO Start zagruzka dannih - ym_hits_stranitsi_new.
root 2023-11-29 11:01:31,224 ERROR Error: oshibka zagruzki v tablitsu - ym_hits_stranitsi_new - Unsigned 64 bit integer datatype is not supported
Traceback (most recent call last):
  File "g:\py.projects\tb\data_collection\ya_metric\zagruzka_v_db.py", line 34, in ya_hits_to_bd
    col.to_sql('ym_hits_stranitsi_new', engine, schema='public', if_exists='append', index=False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\core\generic.py", line 3008, in to_sql
    return sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1948, in to_sql
    table = self.prep_table(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1842, in prep_table
    table = SQLTable(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 899, in __init__
    self.table = self._create_table_setup()
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1205, in _create_table_setup
    column_names_and_types = self._get_column_names_and_types(self._sqlalchemy_type)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1190, in _get_column_names_and_types
    column_names_and_types += [
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1191, in <listcomp>
    (str(self.frame.columns[i]), dtype_mapper(self.frame.iloc[:, i]), False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1339, in _sqlalchemy_type
    raise ValueError("Unsigned 64 bit integer datatype is not supported")
ValueError: Unsigned 64 bit integer datatype is not supported
root 2023-11-29 11:01:31,229 INFO Start zagruzka dannih - ym_hits_obshee_new.
root 2023-11-29 11:01:31,231 ERROR Error: oshibka zagruzki v tablitsu - ym_hits_obshee_new - Unsigned 64 bit integer datatype is not supported
Traceback (most recent call last):
  File "g:\py.projects\tb\data_collection\ya_metric\zagruzka_v_db.py", line 47, in ya_hits_to_bd
    col.to_sql('ym_hits_obshee_new', engine, schema='public', if_exists='append', index=False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\core\generic.py", line 3008, in to_sql
    return sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1948, in to_sql
    table = self.prep_table(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1842, in prep_table
    table = SQLTable(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 899, in __init__
    self.table = self._create_table_setup()
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1205, in _create_table_setup
    column_names_and_types = self._get_column_names_and_types(self._sqlalchemy_type)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1190, in _get_column_names_and_types
    column_names_and_types += [
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1191, in <listcomp>
    (str(self.frame.columns[i]), dtype_mapper(self.frame.iloc[:, i]), False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1339, in _sqlalchemy_type
    raise ValueError("Unsigned 64 bit integer datatype is not supported")
ValueError: Unsigned 64 bit integer datatype is not supported
root 2023-11-29 11:01:31,232 INFO Start zagruzka dannih - ym_hits_deystviya_new.
root 2023-11-29 11:01:31,233 ERROR Error: oshibka zagruzki v tablitsu - ym_hits_deystviya_new - Unsigned 64 bit integer datatype is not supported
Traceback (most recent call last):
  File "g:\py.projects\tb\data_collection\ya_metric\zagruzka_v_db.py", line 60, in ya_hits_to_bd
    col.to_sql('ym_hits_deystviya_new', engine, schema='public', if_exists='append', index=False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\core\generic.py", line 3008, in to_sql
    return sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1948, in to_sql
    table = self.prep_table(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1842, in prep_table
    table = SQLTable(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 899, in __init__
    self.table = self._create_table_setup()
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1205, in _create_table_setup
    column_names_and_types = self._get_column_names_and_types(self._sqlalchemy_type)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1190, in _get_column_names_and_types
    column_names_and_types += [
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1191, in <listcomp>
    (str(self.frame.columns[i]), dtype_mapper(self.frame.iloc[:, i]), False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1339, in _sqlalchemy_type
    raise ValueError("Unsigned 64 bit integer datatype is not supported")
ValueError: Unsigned 64 bit integer datatype is not supported
root 2023-11-29 11:01:31,234 INFO Start zagruzka dannih - ym_hits_ad_new.
root 2023-11-29 11:01:31,235 ERROR Error: oshibka zagruzki v tablitsu - ym_hits_ad_new - Unsigned 64 bit integer datatype is not supported
Traceback (most recent call last):
  File "g:\py.projects\tb\data_collection\ya_metric\zagruzka_v_db.py", line 73, in ya_hits_to_bd
    col.to_sql('ym_hits_ad_new', engine, schema='public', if_exists='append', index=False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\core\generic.py", line 3008, in to_sql
    return sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1948, in to_sql
    table = self.prep_table(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1842, in prep_table
    table = SQLTable(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 899, in __init__
    self.table = self._create_table_setup()
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1205, in _create_table_setup
    column_names_and_types = self._get_column_names_and_types(self._sqlalchemy_type)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1190, in _get_column_names_and_types
    column_names_and_types += [
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1191, in <listcomp>
    (str(self.frame.columns[i]), dtype_mapper(self.frame.iloc[:, i]), False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1339, in _sqlalchemy_type
    raise ValueError("Unsigned 64 bit integer datatype is not supported")
ValueError: Unsigned 64 bit integer datatype is not supported
root 2023-11-29 11:03:39,524 INFO Step_1_visit. Creating a log.
root 2023-11-29 11:03:39,750 INFO Code status 200
NoneType: None
root 2023-11-29 11:03:39,750 INFO Step_1_visit. Successful log request.
root 2023-11-29 11:03:39,775 INFO Step_1_visit. Request number 32806985.
root 2023-11-29 11:03:39,775 INFO Step_1_visit. Request status created.
root 2023-11-29 11:03:39,775 INFO Step_2_visit. Log processing status.
root 2023-11-29 11:03:40,012 INFO Step_2_visit. Loading data. Code 200.
root 2023-11-29 11:04:16,464 INFO Step_2_visit. Number of parts - 0.
root 2023-11-29 11:04:16,464 INFO Step_2_visit. Request status processed.
root 2023-11-29 11:04:16,464 INFO Step_3_visit. Loading the log.
root 2023-11-29 11:04:16,808 INFO Step_3_visit. Loading a log from one part.
root 2023-11-29 11:04:16,808 INFO Step_3_visit. Loading 0 parts of the log.
root 2023-11-29 11:04:16,808 INFO Step_4_visit. Deleting a log.
root 2023-11-29 11:04:17,017 INFO Step_4_visit. Successful log deletion # 32806985.
root 2023-11-29 11:04:17,018 INFO Step_4_visit. Deleting variables.
root 2023-11-29 11:04:17,019 INFO Start clearing data VISITS.
root 2023-11-29 11:04:17,019 INFO Reading data VISITS and writing to a dataframe.
root 2023-11-29 11:04:17,028 INFO Renaming columns VISITS.
root 2023-11-29 11:04:17,029 INFO Clearing data VISITS.
root 2023-11-29 11:04:17,058 INFO Start zagruzka v bazu logs api VISITS.
root 2023-11-29 11:04:17,116 INFO Start zagruzka dannih - ym_visits_obshee_new.
root 2023-11-29 11:04:17,118 ERROR Error: oshibka zagruzki v tablitsu - ym_visits_obshee_new - Unsigned 64 bit integer datatype is not supported
Traceback (most recent call last):
  File "g:\py.projects\tb\data_collection\ya_metric\zagruzka_v_db.py", line 99, in ya_visits_to_bd
    col.to_sql('ym_visits_obshee_new', engine, schema='public', if_exists='append', index=False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\core\generic.py", line 3008, in to_sql
    return sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1948, in to_sql
    table = self.prep_table(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1842, in prep_table
    table = SQLTable(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 899, in __init__
    self.table = self._create_table_setup()
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1205, in _create_table_setup
    column_names_and_types = self._get_column_names_and_types(self._sqlalchemy_type)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1190, in _get_column_names_and_types
    column_names_and_types += [
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1191, in <listcomp>
    (str(self.frame.columns[i]), dtype_mapper(self.frame.iloc[:, i]), False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1339, in _sqlalchemy_type
    raise ValueError("Unsigned 64 bit integer datatype is not supported")
ValueError: Unsigned 64 bit integer datatype is not supported
root 2023-11-29 11:04:17,118 INFO Start zagruzka dannih - # ym_visits_detali_new.
root 2023-11-29 11:04:17,120 ERROR Error: oshibka zagruzki v tablitsu - ym_visits_detali_new - Unsigned 64 bit integer datatype is not supported
Traceback (most recent call last):
  File "g:\py.projects\tb\data_collection\ya_metric\zagruzka_v_db.py", line 113, in ya_visits_to_bd
    col.to_sql('ym_visits_detali_new', engine, schema='public', if_exists='append', index=False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\core\generic.py", line 3008, in to_sql
    return sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1948, in to_sql
    table = self.prep_table(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1842, in prep_table
    table = SQLTable(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 899, in __init__
    self.table = self._create_table_setup()
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1205, in _create_table_setup
    column_names_and_types = self._get_column_names_and_types(self._sqlalchemy_type)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1190, in _get_column_names_and_types
    column_names_and_types += [
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1191, in <listcomp>
    (str(self.frame.columns[i]), dtype_mapper(self.frame.iloc[:, i]), False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1339, in _sqlalchemy_type
    raise ValueError("Unsigned 64 bit integer datatype is not supported")
ValueError: Unsigned 64 bit integer datatype is not supported
root 2023-11-29 11:06:15,278 INFO Step_1_hits. Creating a log.
root 2023-11-29 11:06:15,620 INFO Code status 200
NoneType: None
root 2023-11-29 11:06:15,620 INFO Step_1_hits. Successful log request.
root 2023-11-29 11:06:15,620 INFO Step_1_hits. Request number 32807019.
root 2023-11-29 11:06:15,620 INFO Step_1_hits. Request status created.
root 2023-11-29 11:06:15,620 INFO Step_2_hits. Log processing status.
root 2023-11-29 11:06:15,804 INFO Step_2_hits. Loading data. Code 200.
root 2023-11-29 11:07:07,910 INFO Step_2_hits. Number of parts - 1.
root 2023-11-29 11:07:07,910 INFO Step_2_hits. Request status processed.
root 2023-11-29 11:07:07,910 INFO Step_3_hits. Loading the log.
root 2023-11-29 11:07:08,260 INFO Step_3_hits. Loading a log from one part.
root 2023-11-29 11:07:08,260 INFO Step_4_hits. Deleting a log.
root 2023-11-29 11:07:08,448 INFO Step_4_hits. Successful log deletion # 32807019.
root 2023-11-29 11:07:08,448 INFO Step_4_hits. Deleting variables.
root 2023-11-29 11:07:08,450 INFO Start clearing data HITS.
root 2023-11-29 11:07:08,450 INFO Reading data HITS and writing to a dataframe.
root 2023-11-29 11:07:08,469 INFO Renaming columns HITS.
root 2023-11-29 11:07:08,470 INFO Clearing data HITS.
root 2023-11-29 11:07:08,477 INFO Start zagruzka v bazu logs api HITS.
root 2023-11-29 11:07:08,577 INFO Start zagruzka dannih - ym_hits_stranitsi_new.
root 2023-11-29 11:07:08,579 ERROR Error: oshibka zagruzki v tablitsu - ym_hits_stranitsi_new - Unsigned 64 bit integer datatype is not supported
Traceback (most recent call last):
  File "g:\py.projects\tb\data_collection\ya_metric\zagruzka_v_db.py", line 34, in ya_hits_to_bd
    col.to_sql('ym_hits_stranitsi_new', engine, schema='public', if_exists='append', index=False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\core\generic.py", line 3008, in to_sql
    return sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1948, in to_sql
    table = self.prep_table(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1842, in prep_table
    table = SQLTable(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 899, in __init__
    self.table = self._create_table_setup()
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1205, in _create_table_setup
    column_names_and_types = self._get_column_names_and_types(self._sqlalchemy_type)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1190, in _get_column_names_and_types
    column_names_and_types += [
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1191, in <listcomp>
    (str(self.frame.columns[i]), dtype_mapper(self.frame.iloc[:, i]), False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1339, in _sqlalchemy_type
    raise ValueError("Unsigned 64 bit integer datatype is not supported")
ValueError: Unsigned 64 bit integer datatype is not supported
root 2023-11-29 11:07:08,583 INFO Start zagruzka dannih - ym_hits_obshee_new.
root 2023-11-29 11:07:08,585 ERROR Error: oshibka zagruzki v tablitsu - ym_hits_obshee_new - Unsigned 64 bit integer datatype is not supported
Traceback (most recent call last):
  File "g:\py.projects\tb\data_collection\ya_metric\zagruzka_v_db.py", line 47, in ya_hits_to_bd
    col.to_sql('ym_hits_obshee_new', engine, schema='public', if_exists='append', index=False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\core\generic.py", line 3008, in to_sql
    return sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1948, in to_sql
    table = self.prep_table(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1842, in prep_table
    table = SQLTable(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 899, in __init__
    self.table = self._create_table_setup()
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1205, in _create_table_setup
    column_names_and_types = self._get_column_names_and_types(self._sqlalchemy_type)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1190, in _get_column_names_and_types
    column_names_and_types += [
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1191, in <listcomp>
    (str(self.frame.columns[i]), dtype_mapper(self.frame.iloc[:, i]), False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1339, in _sqlalchemy_type
    raise ValueError("Unsigned 64 bit integer datatype is not supported")
ValueError: Unsigned 64 bit integer datatype is not supported
root 2023-11-29 11:07:08,585 INFO Start zagruzka dannih - ym_hits_deystviya_new.
root 2023-11-29 11:07:08,587 ERROR Error: oshibka zagruzki v tablitsu - ym_hits_deystviya_new - Unsigned 64 bit integer datatype is not supported
Traceback (most recent call last):
  File "g:\py.projects\tb\data_collection\ya_metric\zagruzka_v_db.py", line 60, in ya_hits_to_bd
    col.to_sql('ym_hits_deystviya_new', engine, schema='public', if_exists='append', index=False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\core\generic.py", line 3008, in to_sql
    return sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1948, in to_sql
    table = self.prep_table(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1842, in prep_table
    table = SQLTable(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 899, in __init__
    self.table = self._create_table_setup()
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1205, in _create_table_setup
    column_names_and_types = self._get_column_names_and_types(self._sqlalchemy_type)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1190, in _get_column_names_and_types
    column_names_and_types += [
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1191, in <listcomp>
    (str(self.frame.columns[i]), dtype_mapper(self.frame.iloc[:, i]), False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1339, in _sqlalchemy_type
    raise ValueError("Unsigned 64 bit integer datatype is not supported")
ValueError: Unsigned 64 bit integer datatype is not supported
root 2023-11-29 11:07:08,587 INFO Start zagruzka dannih - ym_hits_ad_new.
root 2023-11-29 11:07:08,588 ERROR Error: oshibka zagruzki v tablitsu - ym_hits_ad_new - Unsigned 64 bit integer datatype is not supported
Traceback (most recent call last):
  File "g:\py.projects\tb\data_collection\ya_metric\zagruzka_v_db.py", line 73, in ya_hits_to_bd
    col.to_sql('ym_hits_ad_new', engine, schema='public', if_exists='append', index=False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\core\generic.py", line 3008, in to_sql
    return sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1948, in to_sql
    table = self.prep_table(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1842, in prep_table
    table = SQLTable(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 899, in __init__
    self.table = self._create_table_setup()
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1205, in _create_table_setup
    column_names_and_types = self._get_column_names_and_types(self._sqlalchemy_type)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1190, in _get_column_names_and_types
    column_names_and_types += [
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1191, in <listcomp>
    (str(self.frame.columns[i]), dtype_mapper(self.frame.iloc[:, i]), False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1339, in _sqlalchemy_type
    raise ValueError("Unsigned 64 bit integer datatype is not supported")
ValueError: Unsigned 64 bit integer datatype is not supported
root 2023-11-29 11:08:30,129 INFO Step_1_visit. Creating a log.
root 2023-11-29 11:08:30,389 INFO Code status 200
NoneType: None
root 2023-11-29 11:08:30,389 INFO Step_1_visit. Successful log request.
root 2023-11-29 11:08:30,389 INFO Step_1_visit. Request number 32807053.
root 2023-11-29 11:08:30,389 INFO Step_1_visit. Request status created.
root 2023-11-29 11:08:30,389 INFO Step_2_visit. Log processing status.
root 2023-11-29 11:08:30,578 INFO Step_2_visit. Loading data. Code 200.
root 2023-11-29 11:09:17,427 INFO Step_2_visit. Number of parts - 0.
root 2023-11-29 11:09:17,427 INFO Step_2_visit. Request status processed.
root 2023-11-29 11:09:17,427 INFO Step_3_visit. Loading the log.
root 2023-11-29 11:09:17,720 INFO Step_3_visit. Loading a log from one part.
root 2023-11-29 11:09:17,720 INFO Step_3_visit. Loading 0 parts of the log.
root 2023-11-29 11:09:17,720 INFO Step_4_visit. Deleting a log.
root 2023-11-29 11:09:17,931 INFO Step_4_visit. Successful log deletion # 32807053.
root 2023-11-29 11:09:17,931 INFO Step_4_visit. Deleting variables.
root 2023-11-29 11:09:17,932 INFO Start clearing data VISITS.
root 2023-11-29 11:09:17,932 INFO Reading data VISITS and writing to a dataframe.
root 2023-11-29 11:09:17,940 INFO Renaming columns VISITS.
root 2023-11-29 11:09:17,942 INFO Clearing data VISITS.
root 2023-11-29 11:09:17,969 INFO Start zagruzka v bazu logs api VISITS.
root 2023-11-29 11:09:18,026 INFO Start zagruzka dannih - ym_visits_obshee_new.
root 2023-11-29 11:09:18,027 ERROR Error: oshibka zagruzki v tablitsu - ym_visits_obshee_new - Unsigned 64 bit integer datatype is not supported
Traceback (most recent call last):
  File "g:\py.projects\tb\data_collection\ya_metric\zagruzka_v_db.py", line 99, in ya_visits_to_bd
    col.to_sql('ym_visits_obshee_new', engine, schema='public', if_exists='append', index=False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\core\generic.py", line 3008, in to_sql
    return sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1948, in to_sql
    table = self.prep_table(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1842, in prep_table
    table = SQLTable(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 899, in __init__
    self.table = self._create_table_setup()
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1205, in _create_table_setup
    column_names_and_types = self._get_column_names_and_types(self._sqlalchemy_type)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1190, in _get_column_names_and_types
    column_names_and_types += [
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1191, in <listcomp>
    (str(self.frame.columns[i]), dtype_mapper(self.frame.iloc[:, i]), False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1339, in _sqlalchemy_type
    raise ValueError("Unsigned 64 bit integer datatype is not supported")
ValueError: Unsigned 64 bit integer datatype is not supported
root 2023-11-29 11:09:18,028 INFO Start zagruzka dannih - # ym_visits_detali_new.
root 2023-11-29 11:09:18,029 ERROR Error: oshibka zagruzki v tablitsu - ym_visits_detali_new - Unsigned 64 bit integer datatype is not supported
Traceback (most recent call last):
  File "g:\py.projects\tb\data_collection\ya_metric\zagruzka_v_db.py", line 113, in ya_visits_to_bd
    col.to_sql('ym_visits_detali_new', engine, schema='public', if_exists='append', index=False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\core\generic.py", line 3008, in to_sql
    return sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1948, in to_sql
    table = self.prep_table(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1842, in prep_table
    table = SQLTable(
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 899, in __init__
    self.table = self._create_table_setup()
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1205, in _create_table_setup
    column_names_and_types = self._get_column_names_and_types(self._sqlalchemy_type)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1190, in _get_column_names_and_types
    column_names_and_types += [
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1191, in <listcomp>
    (str(self.frame.columns[i]), dtype_mapper(self.frame.iloc[:, i]), False)
  File "g:\py.projects\tb\data_collection\.venv\lib\site-packages\pandas\io\sql.py", line 1339, in _sqlalchemy_type
    raise ValueError("Unsigned 64 bit integer datatype is not supported")
ValueError: Unsigned 64 bit integer datatype is not supported
root 2023-11-29 11:40:35,805 INFO Step_1_hits. Creating a log.
root 2023-11-29 11:40:36,197 INFO Code status 200
NoneType: None
root 2023-11-29 11:40:36,198 INFO Step_1_hits. Successful log request.
root 2023-11-29 11:40:36,198 INFO Step_1_hits. Request number 32807461.
root 2023-11-29 11:40:36,198 INFO Step_1_hits. Request status created.
root 2023-11-29 11:40:36,198 INFO Step_2_hits. Log processing status.
root 2023-11-29 11:40:36,405 INFO Step_2_hits. Loading data. Code 200.
root 2023-11-29 11:42:10,417 INFO Step_2_hits. Number of parts - 1.
root 2023-11-29 11:42:10,417 INFO Step_2_hits. Request status processed.
root 2023-11-29 11:42:10,417 INFO Step_3_hits. Loading the log.
root 2023-11-29 11:42:10,812 INFO Step_3_hits. Loading a log from one part.
root 2023-11-29 11:42:10,812 INFO Step_4_hits. Deleting a log.
root 2023-11-29 11:42:11,031 INFO Step_4_hits. Successful log deletion # 32807461.
root 2023-11-29 11:42:11,031 INFO Step_4_hits. Deleting variables.
root 2023-11-29 11:42:11,032 INFO Start clearing data HITS.
root 2023-11-29 11:42:11,032 INFO Reading data HITS and writing to a dataframe.
root 2023-11-29 11:42:11,050 INFO Renaming columns HITS.
root 2023-11-29 11:42:11,052 INFO Clearing data HITS.
root 2023-11-29 11:42:11,058 INFO Start zagruzka v bazu logs api HITS.
root 2023-11-29 11:42:11,288 INFO Start zagruzka dannih - ym_hits_stranitsi_new.
root 2023-11-29 11:42:11,449 INFO End zagruzka dannih - ym_hits_stranitsi_new.
root 2023-11-29 11:42:11,449 INFO Start zagruzka dannih - ym_hits_obshee_new.
root 2023-11-29 11:42:11,597 INFO End zagruzka dannih - ym_hits_obshee_new.
root 2023-11-29 11:42:11,597 INFO Start zagruzka dannih - ym_hits_deystviya_new.
root 2023-11-29 11:42:11,669 INFO End zagruzka dannih - ym_hits_deystviya_new.
root 2023-11-29 11:42:11,670 INFO Start zagruzka dannih - ym_hits_ad_new.
root 2023-11-29 11:42:11,763 INFO End zagruzka dannih - ym_hits_ad_new.
root 2023-11-29 12:01:38,396 INFO Step_1_visit. Creating a log.
root 2023-11-29 12:01:38,716 INFO Code status 200
NoneType: None
root 2023-11-29 12:01:38,716 INFO Step_1_visit. Successful log request.
root 2023-11-29 12:01:38,716 INFO Step_1_visit. Request number 32807661.
root 2023-11-29 12:01:38,716 INFO Step_1_visit. Request status created.
root 2023-11-29 12:01:38,716 INFO Step_2_visit. Log processing status.
root 2023-11-29 12:01:38,908 INFO Step_2_visit. Loading data. Code 200.
root 2023-11-29 12:02:10,269 INFO Step_2_visit. Number of parts - 0.
root 2023-11-29 12:02:10,269 INFO Step_2_visit. Request status processed.
root 2023-11-29 12:02:10,269 INFO Step_3_visit. Loading the log.
root 2023-11-29 12:02:10,620 INFO Step_3_visit. Loading a log from one part.
root 2023-11-29 12:02:10,620 INFO Step_3_visit. Loading 0 parts of the log.
root 2023-11-29 12:02:10,620 INFO Step_4_visit. Deleting a log.
root 2023-11-29 12:02:10,812 INFO Step_4_visit. Successful log deletion # 32807661.
root 2023-11-29 12:02:10,812 INFO Step_4_visit. Deleting variables.
root 2023-11-29 12:02:10,813 INFO Start clearing data VISITS.
root 2023-11-29 12:02:10,813 INFO Reading data VISITS and writing to a dataframe.
root 2023-11-29 12:02:10,828 INFO Renaming columns VISITS.
root 2023-11-29 12:02:10,831 INFO Clearing data VISITS.
root 2023-11-29 12:02:10,888 INFO Start zagruzka v bazu logs api VISITS.
root 2023-11-29 12:02:10,941 INFO Start zagruzka dannih - ym_visits_obshee_new.
root 2023-11-29 12:02:10,987 INFO End zagruzka dannih - ym_visits_obshee_new.
root 2023-11-29 12:02:10,987 INFO Start zagruzka dannih - # ym_visits_detali_new.
root 2023-11-29 12:02:11,015 INFO End zagruzka dannih - ym_visits_detali_new.
